// Code generated by anchor-go. DO NOT EDIT.

package events

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
	solana "github.com/gagliardetto/solana-go"
)

// EventDiscriminators maps event names to discriminators
var EventDiscriminators = map[string][8]byte{
	"CompleteEvent": {95, 114, 97, 156, 212, 46, 152, 8},
	"CompletePumpAmmMigrationEvent": {189, 233, 93, 185, 92, 148, 234, 148},
	"CreateEvent": {27, 114, 169, 77, 222, 235, 99, 118},
	"ExtendAccountEvent": {97, 97, 215, 144, 93, 146, 22, 124},
	"SetParamsEvent": {223, 195, 159, 246, 62, 48, 143, 131},
	"TradeEvent": {189, 219, 127, 211, 78, 230, 97, 238},
	"UpdateGlobalAuthorityEvent": {182, 195, 137, 42, 35, 206, 207, 247},
}

// CompleteEvent represents an event emitted by the program
type CompleteEvent struct {
	User solana.PublicKey
	Mint solana.PublicKey
	BondingCurve solana.PublicKey
	Timestamp int64
}

// CompleteEventDiscriminator is the discriminator for the CompleteEvent event
var CompleteEventDiscriminator = [8]byte{95, 114, 97, 156, 212, 46, 152, 8}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *CompleteEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(CompleteEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field user
	if err := encoder.Encode(e.User); err != nil {
		return fmt.Errorf("failed to encode user: %w", err)
	}
	// Marshal field mint
	if err := encoder.Encode(e.Mint); err != nil {
		return fmt.Errorf("failed to encode mint: %w", err)
	}
	// Marshal field bonding_curve
	if err := encoder.Encode(e.BondingCurve); err != nil {
		return fmt.Errorf("failed to encode bonding_curve: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *CompleteEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(CompleteEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", CompleteEventDiscriminator[:], discriminator)
	}

	// Unmarshal field user
	if err := decoder.Decode(&e.User); err != nil {
		return fmt.Errorf("failed to decode user: %w", err)
	}
	// Unmarshal field mint
	if err := decoder.Decode(&e.Mint); err != nil {
		return fmt.Errorf("failed to decode mint: %w", err)
	}
	// Unmarshal field bonding_curve
	if err := decoder.Decode(&e.BondingCurve); err != nil {
		return fmt.Errorf("failed to decode bonding_curve: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	return nil
}

// ParseCompleteEvent parses a CompleteEvent event from log data
func ParseCompleteEvent(logData []byte) (*CompleteEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != CompleteEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event CompleteEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// CompletePumpAmmMigrationEvent represents an event emitted by the program
type CompletePumpAmmMigrationEvent struct {
	User solana.PublicKey
	Mint solana.PublicKey
	MintAmount uint64
	SolAmount uint64
	PoolMigrationFee uint64
	BondingCurve solana.PublicKey
	Timestamp int64
	Pool solana.PublicKey
}

// CompletePumpAmmMigrationEventDiscriminator is the discriminator for the CompletePumpAmmMigrationEvent event
var CompletePumpAmmMigrationEventDiscriminator = [8]byte{189, 233, 93, 185, 92, 148, 234, 148}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *CompletePumpAmmMigrationEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(CompletePumpAmmMigrationEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field user
	if err := encoder.Encode(e.User); err != nil {
		return fmt.Errorf("failed to encode user: %w", err)
	}
	// Marshal field mint
	if err := encoder.Encode(e.Mint); err != nil {
		return fmt.Errorf("failed to encode mint: %w", err)
	}
	// Marshal field mint_amount
	if err := encoder.Encode(e.MintAmount); err != nil {
		return fmt.Errorf("failed to encode mint_amount: %w", err)
	}
	// Marshal field sol_amount
	if err := encoder.Encode(e.SolAmount); err != nil {
		return fmt.Errorf("failed to encode sol_amount: %w", err)
	}
	// Marshal field pool_migration_fee
	if err := encoder.Encode(e.PoolMigrationFee); err != nil {
		return fmt.Errorf("failed to encode pool_migration_fee: %w", err)
	}
	// Marshal field bonding_curve
	if err := encoder.Encode(e.BondingCurve); err != nil {
		return fmt.Errorf("failed to encode bonding_curve: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	// Marshal field pool
	if err := encoder.Encode(e.Pool); err != nil {
		return fmt.Errorf("failed to encode pool: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *CompletePumpAmmMigrationEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(CompletePumpAmmMigrationEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", CompletePumpAmmMigrationEventDiscriminator[:], discriminator)
	}

	// Unmarshal field user
	if err := decoder.Decode(&e.User); err != nil {
		return fmt.Errorf("failed to decode user: %w", err)
	}
	// Unmarshal field mint
	if err := decoder.Decode(&e.Mint); err != nil {
		return fmt.Errorf("failed to decode mint: %w", err)
	}
	// Unmarshal field mint_amount
	if err := decoder.Decode(&e.MintAmount); err != nil {
		return fmt.Errorf("failed to decode mint_amount: %w", err)
	}
	// Unmarshal field sol_amount
	if err := decoder.Decode(&e.SolAmount); err != nil {
		return fmt.Errorf("failed to decode sol_amount: %w", err)
	}
	// Unmarshal field pool_migration_fee
	if err := decoder.Decode(&e.PoolMigrationFee); err != nil {
		return fmt.Errorf("failed to decode pool_migration_fee: %w", err)
	}
	// Unmarshal field bonding_curve
	if err := decoder.Decode(&e.BondingCurve); err != nil {
		return fmt.Errorf("failed to decode bonding_curve: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	// Unmarshal field pool
	if err := decoder.Decode(&e.Pool); err != nil {
		return fmt.Errorf("failed to decode pool: %w", err)
	}
	return nil
}

// ParseCompletePumpAmmMigrationEvent parses a CompletePumpAmmMigrationEvent event from log data
func ParseCompletePumpAmmMigrationEvent(logData []byte) (*CompletePumpAmmMigrationEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != CompletePumpAmmMigrationEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event CompletePumpAmmMigrationEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// CreateEvent represents an event emitted by the program
type CreateEvent struct {
	Name string
	Symbol string
	Uri string
	Mint solana.PublicKey
	BondingCurve solana.PublicKey
	User solana.PublicKey
	Creator solana.PublicKey
	Timestamp int64
}

// CreateEventDiscriminator is the discriminator for the CreateEvent event
var CreateEventDiscriminator = [8]byte{27, 114, 169, 77, 222, 235, 99, 118}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *CreateEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(CreateEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field name
	if err := encoder.Encode(e.Name); err != nil {
		return fmt.Errorf("failed to encode name: %w", err)
	}
	// Marshal field symbol
	if err := encoder.Encode(e.Symbol); err != nil {
		return fmt.Errorf("failed to encode symbol: %w", err)
	}
	// Marshal field uri
	if err := encoder.Encode(e.Uri); err != nil {
		return fmt.Errorf("failed to encode uri: %w", err)
	}
	// Marshal field mint
	if err := encoder.Encode(e.Mint); err != nil {
		return fmt.Errorf("failed to encode mint: %w", err)
	}
	// Marshal field bonding_curve
	if err := encoder.Encode(e.BondingCurve); err != nil {
		return fmt.Errorf("failed to encode bonding_curve: %w", err)
	}
	// Marshal field user
	if err := encoder.Encode(e.User); err != nil {
		return fmt.Errorf("failed to encode user: %w", err)
	}
	// Marshal field creator
	if err := encoder.Encode(e.Creator); err != nil {
		return fmt.Errorf("failed to encode creator: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *CreateEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(CreateEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", CreateEventDiscriminator[:], discriminator)
	}

	// Unmarshal field name
	if err := decoder.Decode(&e.Name); err != nil {
		return fmt.Errorf("failed to decode name: %w", err)
	}
	// Unmarshal field symbol
	if err := decoder.Decode(&e.Symbol); err != nil {
		return fmt.Errorf("failed to decode symbol: %w", err)
	}
	// Unmarshal field uri
	if err := decoder.Decode(&e.Uri); err != nil {
		return fmt.Errorf("failed to decode uri: %w", err)
	}
	// Unmarshal field mint
	if err := decoder.Decode(&e.Mint); err != nil {
		return fmt.Errorf("failed to decode mint: %w", err)
	}
	// Unmarshal field bonding_curve
	if err := decoder.Decode(&e.BondingCurve); err != nil {
		return fmt.Errorf("failed to decode bonding_curve: %w", err)
	}
	// Unmarshal field user
	if err := decoder.Decode(&e.User); err != nil {
		return fmt.Errorf("failed to decode user: %w", err)
	}
	// Unmarshal field creator
	if err := decoder.Decode(&e.Creator); err != nil {
		return fmt.Errorf("failed to decode creator: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	return nil
}

// ParseCreateEvent parses a CreateEvent event from log data
func ParseCreateEvent(logData []byte) (*CreateEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != CreateEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event CreateEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// ExtendAccountEvent represents an event emitted by the program
type ExtendAccountEvent struct {
	Account solana.PublicKey
	User solana.PublicKey
	CurrentSize uint64
	NewSize uint64
	Timestamp int64
}

// ExtendAccountEventDiscriminator is the discriminator for the ExtendAccountEvent event
var ExtendAccountEventDiscriminator = [8]byte{97, 97, 215, 144, 93, 146, 22, 124}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *ExtendAccountEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(ExtendAccountEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field account
	if err := encoder.Encode(e.Account); err != nil {
		return fmt.Errorf("failed to encode account: %w", err)
	}
	// Marshal field user
	if err := encoder.Encode(e.User); err != nil {
		return fmt.Errorf("failed to encode user: %w", err)
	}
	// Marshal field current_size
	if err := encoder.Encode(e.CurrentSize); err != nil {
		return fmt.Errorf("failed to encode current_size: %w", err)
	}
	// Marshal field new_size
	if err := encoder.Encode(e.NewSize); err != nil {
		return fmt.Errorf("failed to encode new_size: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *ExtendAccountEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(ExtendAccountEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", ExtendAccountEventDiscriminator[:], discriminator)
	}

	// Unmarshal field account
	if err := decoder.Decode(&e.Account); err != nil {
		return fmt.Errorf("failed to decode account: %w", err)
	}
	// Unmarshal field user
	if err := decoder.Decode(&e.User); err != nil {
		return fmt.Errorf("failed to decode user: %w", err)
	}
	// Unmarshal field current_size
	if err := decoder.Decode(&e.CurrentSize); err != nil {
		return fmt.Errorf("failed to decode current_size: %w", err)
	}
	// Unmarshal field new_size
	if err := decoder.Decode(&e.NewSize); err != nil {
		return fmt.Errorf("failed to decode new_size: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	return nil
}

// ParseExtendAccountEvent parses a ExtendAccountEvent event from log data
func ParseExtendAccountEvent(logData []byte) (*ExtendAccountEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != ExtendAccountEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event ExtendAccountEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// SetParamsEvent represents an event emitted by the program
type SetParamsEvent struct {
	InitialVirtualTokenReserves uint64
	InitialVirtualSolReserves uint64
	InitialRealTokenReserves uint64
	FinalRealSolReserves uint64
	TokenTotalSupply uint64
	FeeBasisPoints uint64
	WithdrawAuthority solana.PublicKey
	EnableMigrate bool
	PoolMigrationFee uint64
	CreatorFee uint64
	FeeRecipients [8]solana.PublicKey
	Timestamp int64
}

// SetParamsEventDiscriminator is the discriminator for the SetParamsEvent event
var SetParamsEventDiscriminator = [8]byte{223, 195, 159, 246, 62, 48, 143, 131}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *SetParamsEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(SetParamsEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field initial_virtual_token_reserves
	if err := encoder.Encode(e.InitialVirtualTokenReserves); err != nil {
		return fmt.Errorf("failed to encode initial_virtual_token_reserves: %w", err)
	}
	// Marshal field initial_virtual_sol_reserves
	if err := encoder.Encode(e.InitialVirtualSolReserves); err != nil {
		return fmt.Errorf("failed to encode initial_virtual_sol_reserves: %w", err)
	}
	// Marshal field initial_real_token_reserves
	if err := encoder.Encode(e.InitialRealTokenReserves); err != nil {
		return fmt.Errorf("failed to encode initial_real_token_reserves: %w", err)
	}
	// Marshal field final_real_sol_reserves
	if err := encoder.Encode(e.FinalRealSolReserves); err != nil {
		return fmt.Errorf("failed to encode final_real_sol_reserves: %w", err)
	}
	// Marshal field token_total_supply
	if err := encoder.Encode(e.TokenTotalSupply); err != nil {
		return fmt.Errorf("failed to encode token_total_supply: %w", err)
	}
	// Marshal field fee_basis_points
	if err := encoder.Encode(e.FeeBasisPoints); err != nil {
		return fmt.Errorf("failed to encode fee_basis_points: %w", err)
	}
	// Marshal field withdraw_authority
	if err := encoder.Encode(e.WithdrawAuthority); err != nil {
		return fmt.Errorf("failed to encode withdraw_authority: %w", err)
	}
	// Marshal field enable_migrate
	if err := encoder.Encode(e.EnableMigrate); err != nil {
		return fmt.Errorf("failed to encode enable_migrate: %w", err)
	}
	// Marshal field pool_migration_fee
	if err := encoder.Encode(e.PoolMigrationFee); err != nil {
		return fmt.Errorf("failed to encode pool_migration_fee: %w", err)
	}
	// Marshal field creator_fee
	if err := encoder.Encode(e.CreatorFee); err != nil {
		return fmt.Errorf("failed to encode creator_fee: %w", err)
	}
	// Marshal field fee_recipients
	if err := encoder.Encode(e.FeeRecipients); err != nil {
		return fmt.Errorf("failed to encode fee_recipients: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *SetParamsEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(SetParamsEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", SetParamsEventDiscriminator[:], discriminator)
	}

	// Unmarshal field initial_virtual_token_reserves
	if err := decoder.Decode(&e.InitialVirtualTokenReserves); err != nil {
		return fmt.Errorf("failed to decode initial_virtual_token_reserves: %w", err)
	}
	// Unmarshal field initial_virtual_sol_reserves
	if err := decoder.Decode(&e.InitialVirtualSolReserves); err != nil {
		return fmt.Errorf("failed to decode initial_virtual_sol_reserves: %w", err)
	}
	// Unmarshal field initial_real_token_reserves
	if err := decoder.Decode(&e.InitialRealTokenReserves); err != nil {
		return fmt.Errorf("failed to decode initial_real_token_reserves: %w", err)
	}
	// Unmarshal field final_real_sol_reserves
	if err := decoder.Decode(&e.FinalRealSolReserves); err != nil {
		return fmt.Errorf("failed to decode final_real_sol_reserves: %w", err)
	}
	// Unmarshal field token_total_supply
	if err := decoder.Decode(&e.TokenTotalSupply); err != nil {
		return fmt.Errorf("failed to decode token_total_supply: %w", err)
	}
	// Unmarshal field fee_basis_points
	if err := decoder.Decode(&e.FeeBasisPoints); err != nil {
		return fmt.Errorf("failed to decode fee_basis_points: %w", err)
	}
	// Unmarshal field withdraw_authority
	if err := decoder.Decode(&e.WithdrawAuthority); err != nil {
		return fmt.Errorf("failed to decode withdraw_authority: %w", err)
	}
	// Unmarshal field enable_migrate
	if err := decoder.Decode(&e.EnableMigrate); err != nil {
		return fmt.Errorf("failed to decode enable_migrate: %w", err)
	}
	// Unmarshal field pool_migration_fee
	if err := decoder.Decode(&e.PoolMigrationFee); err != nil {
		return fmt.Errorf("failed to decode pool_migration_fee: %w", err)
	}
	// Unmarshal field creator_fee
	if err := decoder.Decode(&e.CreatorFee); err != nil {
		return fmt.Errorf("failed to decode creator_fee: %w", err)
	}
	// Unmarshal field fee_recipients
	if err := decoder.Decode(&e.FeeRecipients); err != nil {
		return fmt.Errorf("failed to decode fee_recipients: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	return nil
}

// ParseSetParamsEvent parses a SetParamsEvent event from log data
func ParseSetParamsEvent(logData []byte) (*SetParamsEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != SetParamsEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event SetParamsEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// TradeEvent represents an event emitted by the program
type TradeEvent struct {
	Mint solana.PublicKey
	SolAmount uint64
	TokenAmount uint64
	IsBuy bool
	User solana.PublicKey
	Timestamp int64
	VirtualSolReserves uint64
	VirtualTokenReserves uint64
	RealSolReserves uint64
	RealTokenReserves uint64
}

// TradeEventDiscriminator is the discriminator for the TradeEvent event
var TradeEventDiscriminator = [8]byte{189, 219, 127, 211, 78, 230, 97, 238}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *TradeEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(TradeEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field mint
	if err := encoder.Encode(e.Mint); err != nil {
		return fmt.Errorf("failed to encode mint: %w", err)
	}
	// Marshal field sol_amount
	if err := encoder.Encode(e.SolAmount); err != nil {
		return fmt.Errorf("failed to encode sol_amount: %w", err)
	}
	// Marshal field token_amount
	if err := encoder.Encode(e.TokenAmount); err != nil {
		return fmt.Errorf("failed to encode token_amount: %w", err)
	}
	// Marshal field is_buy
	if err := encoder.Encode(e.IsBuy); err != nil {
		return fmt.Errorf("failed to encode is_buy: %w", err)
	}
	// Marshal field user
	if err := encoder.Encode(e.User); err != nil {
		return fmt.Errorf("failed to encode user: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	// Marshal field virtual_sol_reserves
	if err := encoder.Encode(e.VirtualSolReserves); err != nil {
		return fmt.Errorf("failed to encode virtual_sol_reserves: %w", err)
	}
	// Marshal field virtual_token_reserves
	if err := encoder.Encode(e.VirtualTokenReserves); err != nil {
		return fmt.Errorf("failed to encode virtual_token_reserves: %w", err)
	}
	// Marshal field real_sol_reserves
	if err := encoder.Encode(e.RealSolReserves); err != nil {
		return fmt.Errorf("failed to encode real_sol_reserves: %w", err)
	}
	// Marshal field real_token_reserves
	if err := encoder.Encode(e.RealTokenReserves); err != nil {
		return fmt.Errorf("failed to encode real_token_reserves: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *TradeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(TradeEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", TradeEventDiscriminator[:], discriminator)
	}

	// Unmarshal field mint
	if err := decoder.Decode(&e.Mint); err != nil {
		return fmt.Errorf("failed to decode mint: %w", err)
	}
	// Unmarshal field sol_amount
	if err := decoder.Decode(&e.SolAmount); err != nil {
		return fmt.Errorf("failed to decode sol_amount: %w", err)
	}
	// Unmarshal field token_amount
	if err := decoder.Decode(&e.TokenAmount); err != nil {
		return fmt.Errorf("failed to decode token_amount: %w", err)
	}
	// Unmarshal field is_buy
	if err := decoder.Decode(&e.IsBuy); err != nil {
		return fmt.Errorf("failed to decode is_buy: %w", err)
	}
	// Unmarshal field user
	if err := decoder.Decode(&e.User); err != nil {
		return fmt.Errorf("failed to decode user: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	// Unmarshal field virtual_sol_reserves
	if err := decoder.Decode(&e.VirtualSolReserves); err != nil {
		return fmt.Errorf("failed to decode virtual_sol_reserves: %w", err)
	}
	// Unmarshal field virtual_token_reserves
	if err := decoder.Decode(&e.VirtualTokenReserves); err != nil {
		return fmt.Errorf("failed to decode virtual_token_reserves: %w", err)
	}
	// Unmarshal field real_sol_reserves
	if err := decoder.Decode(&e.RealSolReserves); err != nil {
		return fmt.Errorf("failed to decode real_sol_reserves: %w", err)
	}
	// Unmarshal field real_token_reserves
	if err := decoder.Decode(&e.RealTokenReserves); err != nil {
		return fmt.Errorf("failed to decode real_token_reserves: %w", err)
	}
	return nil
}

// ParseTradeEvent parses a TradeEvent event from log data
func ParseTradeEvent(logData []byte) (*TradeEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != TradeEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event TradeEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

// UpdateGlobalAuthorityEvent represents an event emitted by the program
type UpdateGlobalAuthorityEvent struct {
	Global solana.PublicKey
	Authority solana.PublicKey
	NewAuthority solana.PublicKey
	Timestamp int64
}

// UpdateGlobalAuthorityEventDiscriminator is the discriminator for the UpdateGlobalAuthorityEvent event
var UpdateGlobalAuthorityEventDiscriminator = [8]byte{182, 195, 137, 42, 35, 206, 207, 247}

// MarshalWithEncoder implements binary.EncodableWithEncoder
func (e *UpdateGlobalAuthorityEvent) MarshalWithEncoder(encoder *binary.Encoder) error {
	// Write event discriminator
	if err := encoder.WriteBytes(UpdateGlobalAuthorityEventDiscriminator[:], false); err != nil {
		return fmt.Errorf("failed to write discriminator: %w", err)
	}

	// Marshal field global
	if err := encoder.Encode(e.Global); err != nil {
		return fmt.Errorf("failed to encode global: %w", err)
	}
	// Marshal field authority
	if err := encoder.Encode(e.Authority); err != nil {
		return fmt.Errorf("failed to encode authority: %w", err)
	}
	// Marshal field new_authority
	if err := encoder.Encode(e.NewAuthority); err != nil {
		return fmt.Errorf("failed to encode new_authority: %w", err)
	}
	// Marshal field timestamp
	if err := encoder.Encode(e.Timestamp); err != nil {
		return fmt.Errorf("failed to encode timestamp: %w", err)
	}
	return nil
}

// UnmarshalWithDecoder implements binary.DecodableWithDecoder
func (e *UpdateGlobalAuthorityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {
	// Read and verify event discriminator
	discriminator, err := decoder.ReadTypeID()
	if err != nil {
		return fmt.Errorf("failed to read discriminator: %w", err)
	}
	if !discriminator.Equal(UpdateGlobalAuthorityEventDiscriminator[:]) {
		return fmt.Errorf("invalid discriminator: expected %v, got %v", UpdateGlobalAuthorityEventDiscriminator[:], discriminator)
	}

	// Unmarshal field global
	if err := decoder.Decode(&e.Global); err != nil {
		return fmt.Errorf("failed to decode global: %w", err)
	}
	// Unmarshal field authority
	if err := decoder.Decode(&e.Authority); err != nil {
		return fmt.Errorf("failed to decode authority: %w", err)
	}
	// Unmarshal field new_authority
	if err := decoder.Decode(&e.NewAuthority); err != nil {
		return fmt.Errorf("failed to decode new_authority: %w", err)
	}
	// Unmarshal field timestamp
	if err := decoder.Decode(&e.Timestamp); err != nil {
		return fmt.Errorf("failed to decode timestamp: %w", err)
	}
	return nil
}

// ParseUpdateGlobalAuthorityEvent parses a UpdateGlobalAuthorityEvent event from log data
func ParseUpdateGlobalAuthorityEvent(logData []byte) (*UpdateGlobalAuthorityEvent, error) {
	if len(logData) < 8 {
		return nil, fmt.Errorf("log data too short")
	}

	// Check discriminator
	for i := 0; i < 8; i++ {
		if logData[i] != UpdateGlobalAuthorityEventDiscriminator[i] {
			return nil, fmt.Errorf("invalid discriminator")
		}
	}

	// Decode event data
	decoder := binary.NewBorshDecoder(logData[8:])
	var event UpdateGlobalAuthorityEvent
	if err := decoder.Decode(&event); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	return &event, nil
}

