package generator

import (
	"crypto/sha256"
	"fmt"

	"github.com/iamrekas/anchor-go/pkg/idl"
	"github.com/iamrekas/anchor-go/pkg/idl/types"
)

// calculateAccountDiscriminator calculates the discriminator for an account
// In Anchor, account discriminators are calculated as the first 8 bytes of the SHA256 hash of "account:<account_name>"
func calculateAccountDiscriminator(accountName string) [8]byte {
	// Convert account name to PascalCase as per Anchor convention
	pascalCaseName := toCamelCase(accountName)

	// Create the namespace string "account:<account_name>"
	namespace := fmt.Sprintf("account:%s", pascalCaseName)

	// Calculate SHA256 hash
	hash := sha256.Sum256([]byte(namespace))

	// Take the first 8 bytes
	var result [8]byte
	copy(result[:], hash[:8])

	return result
}

// AccountsGenerator generates code for account structures
type AccountsGenerator struct {
	config *Config
}

// NewAccountsGenerator creates a new accounts generator
func NewAccountsGenerator() *AccountsGenerator {
	return &AccountsGenerator{
		config: DefaultConfig(),
	}
}

// Generate implements Generator.Generate
func (g *AccountsGenerator) Generate(idl idl.IDL) ([]*GeneratedFile, error) {
	if len(idl.Accounts()) == 0 {
		// No accounts to generate
		return nil, nil
	}

	// Create a file for accounts
	file := &GeneratedFile{
		Name: "accounts",
		Path: g.config.DstDir,
	}

	// Generate code for each account
	var content string
	content += fmt.Sprintf("// Code generated by anchor-go. DO NOT EDIT.\n\n")
	content += fmt.Sprintf("package %s\n\n", g.config.Package)

	// Add imports
	content += "import (\n"
	content += "\t\"fmt\"\n"
	content += "\tbinary \"github.com/gagliardetto/binary\"\n"
	content += "\tsolana \"github.com/gagliardetto/solana-go\"\n"
	content += ")\n\n"

	// Generate code for each account
	for _, account := range idl.Accounts() {
		content += g.generateAccount(account, idl)
	}

	file.Content = []byte(content)
	return []*GeneratedFile{file}, nil
}

// SetConfig implements Generator.SetConfig
func (g *AccountsGenerator) SetConfig(config *Config) {
	g.config = config
}

// GetConfig implements Generator.GetConfig
func (g *AccountsGenerator) GetConfig() *Config {
	return g.config
}

// generateAccount generates code for a single account
func (g *AccountsGenerator) generateAccount(account idl.AccountDef, _idl idl.IDL) string {
	var code string

	// Add documentation
	if len(account.Docs) > 0 {
		code += "// " + account.Name + " represents an account in the program\n"
		for _, doc := range account.Docs {
			code += "// " + doc + "\n"
		}
	} else {
		code += "// " + account.Name + " represents an account in the program\n"
	}

	// Generate struct definition with Account suffix
	code += fmt.Sprintf("type %sAccount struct {\n", account.Name)

	// Track used field names to handle duplicates
	// AIDEV-NOTE: Deduplicate field names by adding suffix when conflicts occur
	usedFieldNames := make(map[string]int)

	// Generate fields
	for _, field := range account.Type.Fields {
		if len(field.Docs) > 0 {
			for _, doc := range field.Docs {
				code += "\t// " + doc + "\n"
			}
		}

		// Generate field with type
		fieldType := g.generateFieldType(field.Type, _idl)
		// Capitalize the first letter of the field name to make it public
		baseFieldName := toCamelCase(field.Name)
		
		// Handle duplicate field names
		fieldName := baseFieldName
		if count, exists := usedFieldNames[baseFieldName]; exists {
			// Add suffix for duplicate field names
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			usedFieldNames[baseFieldName] = count + 1
		} else {
			usedFieldNames[baseFieldName] = 1
		}
		
		// option<T> arrives as Optional[T] from generateFieldType; "optional: true"
		// on a non-option type is wrapped here. Both flow through the wrapper's
		// self-(un)marshal so the bin:"optional" tag is no longer needed.
		if field.Optional && !field.Type.IsOption() {
			code += fmt.Sprintf("\t%s Optional[%s]\n", fieldName, fieldType)
		} else {
			code += fmt.Sprintf("\t%s %s\n", fieldName, fieldType)
		}
	}

	code += "}\n\n"

	// Only generate discriminator for non-Uint8TypeID encoding
	if g.config.TypeID != TypeIDUint8 {
		// Generate discriminator constant
		// Use discriminator from IDL if available, otherwise calculate it
		var discriminator [8]byte
		if account.Discriminator != nil && len(account.Discriminator) == 8 {
			for i, b := range account.Discriminator {
				discriminator[i] = b
			}
		} else {
			discriminator = calculateAccountDiscriminator(account.Name)
		}

		code += fmt.Sprintf("// %sDiscriminator is the discriminator for the %s account\n", account.Name, account.Name)
		code += fmt.Sprintf("var %sDiscriminator = [8]byte{", account.Name)
		for i, b := range discriminator {
			if i > 0 {
				code += ", "
			}
			code += fmt.Sprintf("%d", b)
		}
		code += "}\n\n"
	}

	// Generate MarshalWithEncoder method
	code += fmt.Sprintf("// MarshalWithEncoder implements binary.EncodableWithEncoder\n")
	code += fmt.Sprintf("func (a *%sAccount) MarshalWithEncoder(encoder *binary.Encoder) error {\n", account.Name)

	// Only write discriminator for non-Uint8TypeID encoding
	if g.config.TypeID != TypeIDUint8 {
		code += fmt.Sprintf("\t// Write account discriminator\n")
		code += fmt.Sprintf("\tif err := encoder.WriteBytes(%sDiscriminator[:], false); err != nil {\n", account.Name)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to write discriminator: %%w\", err)\n")
		code += fmt.Sprintf("\t}\n\n")
	}

	// Track used field names again for marshal method
	// AIDEV-NOTE: Need to regenerate deduplicated names for marshal/unmarshal methods
	marshalUsedNames := make(map[string]int)

	// Marshal fields
	for _, field := range account.Type.Fields {
		baseFieldName := toCamelCase(field.Name)
		
		// Handle duplicate field names (same logic as struct generation)
		fieldName := baseFieldName
		if count, exists := marshalUsedNames[baseFieldName]; exists {
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			marshalUsedNames[baseFieldName] = count + 1
		} else {
			marshalUsedNames[baseFieldName] = 1
		}
		
		// Optional[T] (the wrapper for both option<T> and "optional: true")
		// self-marshals; plain fields use the normal Encode path.
		code += fmt.Sprintf("\t// Marshal field %s\n", field.Name)
		code += fmt.Sprintf("\tif err := encoder.Encode(a.%s); err != nil {\n", fieldName)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to encode %s: %%w\", err)\n", field.Name)
		code += fmt.Sprintf("\t}\n")
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	// Generate UnmarshalWithDecoder method
	code += fmt.Sprintf("// UnmarshalWithDecoder implements binary.DecodableWithDecoder\n")
	code += fmt.Sprintf("func (a *%sAccount) UnmarshalWithDecoder(decoder *binary.Decoder) error {\n", account.Name)

	// Only read and verify discriminator for non-Uint8TypeID encoding
	if g.config.TypeID != TypeIDUint8 {
		code += fmt.Sprintf("\t// Read and verify account discriminator\n")
		code += fmt.Sprintf("\tdiscriminator, err := decoder.ReadTypeID()\n")
		code += fmt.Sprintf("\tif err != nil {\n")
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to read discriminator: %%w\", err)\n")
		code += fmt.Sprintf("\t}\n")
		code += fmt.Sprintf("\tif !discriminator.Equal(%sDiscriminator[:]) {\n", account.Name)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"invalid discriminator: expected %%v, got %%v\", %sDiscriminator[:], discriminator)\n", account.Name)
		code += fmt.Sprintf("\t}\n\n")
	}

	// Track used field names again for unmarshal method
	// AIDEV-NOTE: Need to regenerate deduplicated names for unmarshal method
	unmarshalUsedNames := make(map[string]int)

	// Unmarshal fields
	for _, field := range account.Type.Fields {
		baseFieldName := toCamelCase(field.Name)
		
		// Handle duplicate field names (same logic as struct generation)
		fieldName := baseFieldName
		if count, exists := unmarshalUsedNames[baseFieldName]; exists {
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			unmarshalUsedNames[baseFieldName] = count + 1
		} else {
			unmarshalUsedNames[baseFieldName] = 1
		}
		
		// Optional[T] handles its own presence byte; plain fields use Decode.
		code += fmt.Sprintf("\t// Unmarshal field %s\n", field.Name)
		code += fmt.Sprintf("\tif err := decoder.Decode(&a.%s); err != nil {\n", fieldName)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to decode %s: %%w\", err)\n", field.Name)
		code += fmt.Sprintf("\t}\n")
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	return code
}

// generateFieldType generates Go type for an IDL type
func (g *AccountsGenerator) generateFieldType(t idl.Type, _idl idl.IDL) string {
	if t.IsBasic() {
		// Map basic types to Go types
		switch t.String() {
		case "bool":
			return "bool"
		case "u8":
			return "uint8"
		case "i8":
			return "int8"
		case "u16":
			return "uint16"
		case "i16":
			return "int16"
		case "u32":
			return "uint32"
		case "i32":
			return "int32"
		case "u64":
			return "uint64"
		case "i64":
			return "int64"
		case "u128":
			return "binary.Uint128"
		case "i128":
			return "binary.Int128"
		case "bytes":
			return "[]byte"
		case "string":
			return "string"
		case "publicKey", "pubkey":
			return "solana.PublicKey"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		case "unixTimestamp":
			return "solana.UnixTimeSeconds"
		case "hash":
			return "solana.Hash"
		case "duration":
			return "solana.DurationSeconds"
		default:
			return "interface{}"
		}
	} else if t.IsArray() {
		// Handle array types
		arrayType := t.(interface {
			ElementType() idl.Type
			Size() int
		})
		elemType := g.generateFieldType(arrayType.ElementType(), _idl)
		return fmt.Sprintf("[%d]%s", arrayType.Size(), elemType)
	} else if t.IsVector() {
		// Handle vector types
		// AIDEV-NOTE: VectorType has ElementType field, not method
		vecType := t.(*types.VectorType)
		elemType := g.generateFieldType(vecType.ElementType, _idl)
		return fmt.Sprintf("[]%s", elemType)
	} else if t.IsOption() {
		// Borsh option<T>: rendered as the generic wrapper Optional[T] (see types.go).
		optType := t.(*types.OptionType)
		elemType := g.generateFieldType(optType.ElementType, _idl)
		return fmt.Sprintf("Optional[%s]", elemType)
	} else if t.IsDefined() {
		// Handle defined types
		typeName := t.String()

		// Check if this type is an account type in the IDL
		for _, account := range _idl.Accounts() {
			if account.Name == typeName {
				// If it's an account type, append "Account" suffix
				return typeName + "Account"
			}
		}

		return typeName
	}

	return "interface{}"
}
