package generator

import (
	"fmt"

	"github.com/iamrekas/anchor-go/pkg/idl"
)

// ErrorsGenerator generates code for program errors
type ErrorsGenerator struct {
	config *Config
}

// NewErrorsGenerator creates a new errors generator
func NewErrorsGenerator() *ErrorsGenerator {
	return &ErrorsGenerator{
		config: DefaultConfig(),
	}
}

// Generate implements Generator.Generate
func (g *ErrorsGenerator) Generate(idl idl.IDL) ([]*GeneratedFile, error) {
	if len(idl.Errors()) == 0 {
		// No errors to generate
		return nil, nil
	}

	// Create a file for errors
	file := &GeneratedFile{
		Name: "errors",
		Path: g.config.DstDir,
	}

	// Generate code for errors
	var content string
	content += fmt.Sprintf("// Code generated by anchor-go. DO NOT EDIT.\n\n")
	content += fmt.Sprintf("package %s\n\n", g.config.Package)

	// Add imports
	content += "import (\n"
	content += "\t\"fmt\"\n"
	content += ")\n\n"

	// Generate error codes
	content += "// Error codes\n"
	content += "const (\n"
	for _, err := range idl.Errors() {
		content += fmt.Sprintf("\t%sErrorCode = %d // %s\n", toCamelCase(err.Name), err.Code, err.Msg)
	}
	content += ")\n\n"

	// Generate error map
	content += "// ErrorMessages maps error codes to error messages\n"
	content += "var ErrorMessages = map[uint32]string{\n"
	for _, err := range idl.Errors() {
		content += fmt.Sprintf("\t%d: \"%s\",\n", err.Code, err.Msg)
	}
	content += "}\n\n"

	// Generate error type
	content += "// ProgramError represents a program error\n"
	content += "type ProgramError struct {\n"
	content += "\tCode uint32\n"
	content += "\tMsg  string\n"
	content += "}\n\n"

	// Generate Error method
	content += "// Error implements the error interface\n"
	content += "func (e *ProgramError) Error() string {\n"
	content += "\treturn fmt.Sprintf(\"Program error: %d - %s\", e.Code, e.Msg)\n"
	content += "}\n\n"

	// Generate NewProgramError function
	content += "// NewProgramError creates a new program error\n"
	content += "func NewProgramError(code uint32) *ProgramError {\n"
	content += "\tmsg, ok := ErrorMessages[code]\n"
	content += "\tif !ok {\n"
	content += "\t\tmsg = \"Unknown error\"\n"
	content += "\t}\n"
	content += "\treturn &ProgramError{\n"
	content += "\t\tCode: code,\n"
	content += "\t\tMsg:  msg,\n"
	content += "\t}\n"
	content += "}\n\n"

	// Generate error constructor functions
	for _, err := range idl.Errors() {
		content += fmt.Sprintf("// New%sError creates a new %s error\n", toCamelCase(err.Name), err.Name)
		content += fmt.Sprintf("func New%sError() *ProgramError {\n", toCamelCase(err.Name))
		content += fmt.Sprintf("\treturn NewProgramError(%sErrorCode)\n", toCamelCase(err.Name))
		content += "}\n\n"
	}

	file.Content = []byte(content)
	return []*GeneratedFile{file}, nil
}

// SetConfig implements Generator.SetConfig
func (g *ErrorsGenerator) SetConfig(config *Config) {
	g.config = config
}

// GetConfig implements Generator.GetConfig
func (g *ErrorsGenerator) GetConfig() *Config {
	return g.config
}
