package generator

import (
	"crypto/sha256"
	"fmt"

	"github.com/iamrekas/anchor-go/pkg/idl"
	"github.com/iamrekas/anchor-go/pkg/idl/types"
	"github.com/iamrekas/anchor-go/sighash"
)

// EventsGenerator generates code for program events
type EventsGenerator struct {
	config *Config
}

// NewEventsGenerator creates a new events generator
func NewEventsGenerator() *EventsGenerator {
	return &EventsGenerator{
		config: DefaultConfig(),
	}
}

// calculateEventDiscriminator calculates the discriminator for an event
// In Anchor, event discriminators are calculated as the first 8 bytes of the SHA256 hash of "event:<event_name>"
func calculateEventDiscriminator(eventName string) [8]byte {
	// Convert event name to snake_case as per Anchor convention
	snakeCaseName := sighash.ToSnakeForSighash(eventName)

	// Create the namespace string "event:<event_name>"
	namespace := fmt.Sprintf("event:%s", snakeCaseName)

	// Calculate SHA256 hash
	hash := sha256.Sum256([]byte(namespace))

	// Take the first 8 bytes
	var result [8]byte
	copy(result[:], hash[:8])

	return result
}

// Generate implements Generator.Generate
func (g *EventsGenerator) Generate(idl idl.IDL) ([]*GeneratedFile, error) {
	if len(idl.Events()) == 0 {
		// No events to generate
		return nil, nil
	}

	// Create a file for events
	file := &GeneratedFile{
		Name: "events",
		Path: g.config.DstDir,
	}

	// Generate code for each event
	var content string
	content += fmt.Sprintf("// Code generated by anchor-go. DO NOT EDIT.\n\n")
	content += fmt.Sprintf("package %s\n\n", g.config.Package)

	// Add imports
	content += "import (\n"
	content += "\t\"fmt\"\n"
	content += "\tbinary \"github.com/gagliardetto/binary\"\n"
	content += "\tsolana \"github.com/gagliardetto/solana-go\"\n"
	content += ")\n\n"

	// Generate event discriminator map
	content += "// EventDiscriminators maps event names to discriminators\n"
	content += "var EventDiscriminators = map[string][8]byte{\n"
	for _, event := range idl.Events() {
		content += fmt.Sprintf("\t\"%s\": {", event.Name)

		// Use discriminator from IDL if available, otherwise calculate it
		var discriminator [8]byte
		if event.Discriminator != nil && len(event.Discriminator) == 8 {
			for i, b := range event.Discriminator {
				discriminator[i] = b
			}
		} else {
			discriminator = calculateEventDiscriminator(event.Name)
		}

		// Format the discriminator bytes
		for i, b := range discriminator {
			if i > 0 {
				content += ", "
			}
			content += fmt.Sprintf("%d", b)
		}
		content += "},\n"
	}
	content += "}\n\n"

	// Generate code for each event
	for _, event := range idl.Events() {
		content += g.generateEvent(event)
	}

	file.Content = []byte(content)
	return []*GeneratedFile{file}, nil
}

// SetConfig implements Generator.SetConfig
func (g *EventsGenerator) SetConfig(config *Config) {
	g.config = config
}

// GetConfig implements Generator.GetConfig
func (g *EventsGenerator) GetConfig() *Config {
	return g.config
}

// generateEvent generates code for a single event
func (g *EventsGenerator) generateEvent(event idl.Event) string {
	var code string

	// Add documentation
	if len(event.Docs) > 0 {
		code += "// " + event.Name + " represents an event emitted by the program\n"
		for _, doc := range event.Docs {
			code += "// " + doc + "\n"
		}
	} else {
		code += "// " + event.Name + " represents an event emitted by the program\n"
	}

	// Generate struct definition with Event suffix to avoid conflicts with types
	code += fmt.Sprintf("type %sEvent struct {\n", event.Name)

	// Generate fields
	for _, field := range event.Fields {
		if len(field.Docs) > 0 {
			for _, doc := range field.Docs {
				code += "\t// " + doc + "\n"
			}
		}

		// Generate field with type
		fieldType := g.generateFieldType(field.Type)
		if field.Optional {
			code += fmt.Sprintf("\t%s *%s `bin:\"optional\"`\n", toCamelCase(field.Name), fieldType)
		} else {
			code += fmt.Sprintf("\t%s %s\n", toCamelCase(field.Name), fieldType)
		}
	}

	code += "}\n\n"

	// Generate discriminator constant
	// Use discriminator from IDL if available, otherwise calculate it
	var discriminator [8]byte
	if event.Discriminator != nil && len(event.Discriminator) == 8 {
		for i, b := range event.Discriminator {
			discriminator[i] = b
		}
	} else {
		discriminator = calculateEventDiscriminator(event.Name)
	}

	code += fmt.Sprintf("// %sEventDiscriminator is the discriminator for the %s event\n", event.Name, event.Name)
	code += fmt.Sprintf("var %sEventDiscriminator = [8]byte{", event.Name)
	for i, b := range discriminator {
		if i > 0 {
			code += ", "
		}
		code += fmt.Sprintf("%d", b)
	}
	code += "}\n\n"

	// Generate MarshalWithEncoder method
	code += fmt.Sprintf("// MarshalWithEncoder implements binary.EncodableWithEncoder\n")
	code += fmt.Sprintf("func (e *%sEvent) MarshalWithEncoder(encoder *binary.Encoder) error {\n", event.Name)
	code += fmt.Sprintf("\t// Write event discriminator\n")
	code += fmt.Sprintf("\tif err := encoder.WriteBytes(%sEventDiscriminator[:], false); err != nil {\n", event.Name)
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to write discriminator: %%w\", err)\n")
	code += fmt.Sprintf("\t}\n\n")

	// Marshal fields
	for _, field := range event.Fields {
		if field.Optional {
			code += fmt.Sprintf("\t// Marshal optional field %s\n", field.Name)
			code += fmt.Sprintf("\tif e.%s == nil {\n", toCamelCase(field.Name))
			code += fmt.Sprintf("\t\tif err := encoder.WriteBool(false); err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to write optional flag for %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t} else {\n")
			code += fmt.Sprintf("\t\tif err := encoder.WriteBool(true); err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to write optional flag for %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t\tif err := encoder.Encode(e.%s); err != nil {\n", toCamelCase(field.Name))
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to encode %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t}\n")
		} else {
			code += fmt.Sprintf("\t// Marshal field %s\n", field.Name)
			code += fmt.Sprintf("\tif err := encoder.Encode(e.%s); err != nil {\n", toCamelCase(field.Name))
			code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to encode %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t}\n")
		}
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	// Generate UnmarshalWithDecoder method
	code += fmt.Sprintf("// UnmarshalWithDecoder implements binary.DecodableWithDecoder\n")
	code += fmt.Sprintf("func (e *%sEvent) UnmarshalWithDecoder(decoder *binary.Decoder) error {\n", event.Name)
	code += fmt.Sprintf("\t// Read and verify event discriminator\n")
	code += fmt.Sprintf("\tdiscriminator, err := decoder.ReadTypeID()\n")
	code += fmt.Sprintf("\tif err != nil {\n")
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to read discriminator: %%w\", err)\n")
	code += fmt.Sprintf("\t}\n")
	code += fmt.Sprintf("\tif !discriminator.Equal(%sEventDiscriminator[:]) {\n", event.Name)
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"invalid discriminator: expected %%v, got %%v\", %sEventDiscriminator[:], discriminator)\n", event.Name)
	code += fmt.Sprintf("\t}\n\n")

	// Unmarshal fields
	for _, field := range event.Fields {
		if field.Optional {
			code += fmt.Sprintf("\t// Unmarshal optional field %s\n", field.Name)
			code += fmt.Sprintf("\thasValue, err := decoder.ReadBool()\n")
			code += fmt.Sprintf("\tif err != nil {\n")
			code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to read optional flag for %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t}\n")
			code += fmt.Sprintf("\tif hasValue {\n")
			code += fmt.Sprintf("\t\te.%s = new(%s)\n", toCamelCase(field.Name), g.generateFieldType(field.Type))
			code += fmt.Sprintf("\t\tif err := decoder.Decode(e.%s); err != nil {\n", toCamelCase(field.Name))
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to decode %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t}\n")
		} else {
			code += fmt.Sprintf("\t// Unmarshal field %s\n", field.Name)
			code += fmt.Sprintf("\tif err := decoder.Decode(&e.%s); err != nil {\n", toCamelCase(field.Name))
			code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to decode %s: %%w\", err)\n", field.Name)
			code += fmt.Sprintf("\t}\n")
		}
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	// Generate ParseEvent function
	code += fmt.Sprintf("// Parse%sEvent parses a %s event from log data\n", event.Name, event.Name)
	code += fmt.Sprintf("func Parse%sEvent(logData []byte) (*%sEvent, error) {\n", event.Name, event.Name)
	code += fmt.Sprintf("\tif len(logData) < 8 {\n")
	code += fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"log data too short\")\n")
	code += fmt.Sprintf("\t}\n\n")
	code += fmt.Sprintf("\t// Check discriminator\n")
	code += fmt.Sprintf("\tfor i := 0; i < 8; i++ {\n")
	code += fmt.Sprintf("\t\tif logData[i] != %sEventDiscriminator[i] {\n", event.Name)
	code += fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"invalid discriminator\")\n")
	code += fmt.Sprintf("\t\t}\n")
	code += fmt.Sprintf("\t}\n\n")
	code += fmt.Sprintf("\t// Decode event data\n")
	code += fmt.Sprintf("\tdecoder := binary.NewBorshDecoder(logData[8:])\n")
	code += fmt.Sprintf("\tvar event %sEvent\n", event.Name)
	code += fmt.Sprintf("\tif err := decoder.Decode(&event); err != nil {\n")
	code += fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"failed to decode event: %%w\", err)\n")
	code += fmt.Sprintf("\t}\n\n")
	code += fmt.Sprintf("\treturn &event, nil\n")
	code += fmt.Sprintf("}\n\n")

	return code
}

// generateFieldType generates Go type for an IDL type
func (g *EventsGenerator) generateFieldType(t idl.Type) string {
	if t.IsBasic() {
		// Map basic types to Go types
		switch t.String() {
		case "bool":
			return "bool"
		case "u8":
			return "uint8"
		case "i8":
			return "int8"
		case "u16":
			return "uint16"
		case "i16":
			return "int16"
		case "u32":
			return "uint32"
		case "i32":
			return "int32"
		case "u64":
			return "uint64"
		case "i64":
			return "int64"
		case "u128":
			return "binary.Uint128"
		case "i128":
			return "binary.Int128"
		case "bytes":
			return "[]byte"
		case "string":
			return "string"
		case "publicKey", "pubkey":
			return "solana.PublicKey"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		case "unixTimestamp":
			return "solana.UnixTimeSeconds"
		case "hash":
			return "solana.Hash"
		case "duration":
			return "solana.DurationSeconds"
		default:
			return "interface{}"
		}
	} else if t.IsArray() {
		// Handle array types
		arrayType := t.(interface {
			ElementType() idl.Type
			Size() int
		})
		elemType := g.generateFieldType(arrayType.ElementType())
		return fmt.Sprintf("[%d]%s", arrayType.Size(), elemType)
	} else if t.IsVector() {
		// Handle vector types
		vecType, ok := t.(*types.VectorType)
		if !ok {
			return "interface{}"
		}
		elemType := g.generateFieldType(vecType.ElementType)
		return fmt.Sprintf("[]%s", elemType)
	} else if t.IsOption() {
		// Handle option types
		optType, ok := t.(*types.OptionType)
		if !ok {
			return "interface{}"
		}
		elemType := g.generateFieldType(optType.ElementType)
		return fmt.Sprintf("*%s", elemType)
	} else if t.IsDefined() {
		// Handle defined types
		return t.String()
	}

	return "interface{}"
}
