package generator

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/iamrekas/anchor-go/pkg/idl"
	"github.com/iamrekas/anchor-go/pkg/idl/types"
	"github.com/iamrekas/anchor-go/sighash"
)

// calculateInstructionDiscriminator calculates the discriminator for an instruction
// In Anchor, instruction discriminators are calculated as the first 8 bytes of the SHA256 hash of "global:<instruction_name>"
func calculateInstructionDiscriminator(instructionName string) [8]byte {
	// Convert instruction name to snake_case as per Anchor convention
	snakeCaseName := sighash.ToSnakeForSighash(instructionName)

	// Create the namespace string "global:<instruction_name>"
	namespace := fmt.Sprintf("global:%s", snakeCaseName)

	// Calculate SHA256 hash
	hash := sha256.Sum256([]byte(namespace))

	// Take the first 8 bytes
	var result [8]byte
	copy(result[:], hash[:8])

	return result
}

// InstructionsGenerator generates code for program instructions
type InstructionsGenerator struct {
	config *Config
}

// NewInstructionsGenerator creates a new instructions generator
func NewInstructionsGenerator() *InstructionsGenerator {
	return &InstructionsGenerator{
		config: DefaultConfig(),
	}
}

// Generate implements Generator.Generate
func (g *InstructionsGenerator) Generate(idl idl.IDL) ([]*GeneratedFile, error) {
	if g.config.Verbose {
		fmt.Printf("Instructions generator: found %d instructions\n", len(idl.Instructions()))
	}

	if len(idl.Instructions()) == 0 {
		// No instructions to generate
		return nil, nil
	}

	files := make([]*GeneratedFile, 0)

	// Generate the main instructions.go file
	mainFile, err := g.generateMainInstructionsFile(idl)
	if err != nil {
		return nil, err
	}
	files = append(files, mainFile)

	// Generate individual instruction files
	for _, instr := range idl.Instructions() {
		instrFile, err := g.generateInstructionFile(idl, instr)
		if err != nil {
			return nil, err
		}
		files = append(files, instrFile)
	}

	return files, nil
}

// SetConfig implements Generator.SetConfig
func (g *InstructionsGenerator) SetConfig(config *Config) {
	g.config = config
}

// GetConfig implements Generator.GetConfig
func (g *InstructionsGenerator) GetConfig() *Config {
	return g.config
}

// generateMainInstructionsFile generates the main instructions.go file
func (g *InstructionsGenerator) generateMainInstructionsFile(idl idl.IDL) (*GeneratedFile, error) {
	file := &GeneratedFile{
		Name: "instructions",
		Path: g.config.DstDir,
	}

	var content bytes.Buffer
	content.WriteString("// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.\n\n")
	content.WriteString(fmt.Sprintf("package %s\n\n", g.config.Package))

	// Add imports
	content.WriteString("import (\n")
	content.WriteString("\t\"bytes\"\n")
	content.WriteString("\t\"fmt\"\n")
	content.WriteString("\tag_spew \"github.com/davecgh/go-spew/spew\"\n")
	content.WriteString("\tag_binary \"github.com/gagliardetto/binary\"\n")
	content.WriteString("\tag_solanago \"github.com/gagliardetto/solana-go\"\n")
	content.WriteString("\tag_text \"github.com/gagliardetto/solana-go/text\"\n")
	content.WriteString("\tag_treeout \"github.com/gagliardetto/treeout\"\n")
	content.WriteString(")\n\n")

	// Generate program ID variable
	content.WriteString("var ProgramID ag_solanago.PublicKey\n\n")

	// Generate SetProgramID function
	content.WriteString("func SetProgramID(PublicKey ag_solanago.PublicKey) {\n")
	content.WriteString("\tProgramID = PublicKey\n")
	content.WriteString("\tag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)\n")
	content.WriteString("}\n\n")

	// Generate program name constant
	content.WriteString(fmt.Sprintf("const ProgramName = \"%s\"\n\n", toCamelCase(g.config.Package)))

	// Generate init function
	content.WriteString("func init() {\n")
	content.WriteString("\tif !ProgramID.IsZero() {\n")
	content.WriteString("\t\tag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)\n")
	content.WriteString("\t}\n")
	content.WriteString("}\n\n")

	// Generate instruction discriminators
	content.WriteString("var (\n")
	content.WriteString("\t// Versioned Instructions\n")

	// For TypeIDUint8, TypeIDUint32, and TypeIDUvarint32, we'll use iota-like sequential values
	// For other types, we'll use the discriminator from the IDL
	switch g.config.TypeID {
	case TypeIDUint8:
		// For Uint8TypeIDEncoding, use sequential uint8 values (0, 1, 2, ...)
		content.WriteString("\t// Using sequential uint8 values for instruction discriminators\n")
		for i, instr := range idl.Instructions() {
			instrName := toCamelCase(instr.Name)
			content.WriteString(fmt.Sprintf("\tInstruction_%s = ag_binary.TypeIDFromUint8(%d)\n\n", instrName, i))
		}
	case TypeIDUint32:
		// For Uint32TypeIDEncoding, use sequential uint32 values (0, 1, 2, ...)
		content.WriteString("\t// Using sequential uint32 values for instruction discriminators\n")
		for i, instr := range idl.Instructions() {
			instrName := toCamelCase(instr.Name)
			content.WriteString(fmt.Sprintf("\tInstruction_%s = ag_binary.TypeIDFromUint32(%d, ag_binary.LittleEndian)\n\n", instrName, i))
		}
	case TypeIDUvarint32:
		// For Uvarint32TypeIDEncoding, use sequential uvarint32 values (0, 1, 2, ...)
		content.WriteString("\t// Using sequential uvarint32 values for instruction discriminators\n")
		for i, instr := range idl.Instructions() {
			instrName := toCamelCase(instr.Name)
			content.WriteString(fmt.Sprintf("\tInstruction_%s = ag_binary.TypeIDFromUvarint32(%d)\n\n", instrName, i))
		}
	case TypeIDNoType:
		// For NoTypeIDEncoding, use a default ID
		content.WriteString("\t// Using NoTypeIDDefaultID for instruction discriminators\n")
		for _, instr := range idl.Instructions() {
			instrName := toCamelCase(instr.Name)
			content.WriteString(fmt.Sprintf("\tInstruction_%s = ag_binary.NoTypeIDDefaultID\n\n", instrName))
		}
	default:
		// Default to AnchorTypeIDEncoding (full 8-byte array from discriminator)
		content.WriteString("\t// Using Anchor sighash discriminators\n")
		for _, instr := range idl.Instructions() {
			instrName := toCamelCase(instr.Name)
			content.WriteString(fmt.Sprintf("\tInstruction_%s = ag_binary.TypeID([8]byte{", instrName))

			// Use discriminator from IDL if available, otherwise calculate it
			var discriminator [8]byte
			if instr.Discriminator != nil && len(instr.Discriminator) == 8 {
				for i, b := range instr.Discriminator {
					discriminator[i] = b
				}
			} else {
				// Force create discriminator when empty and using AnchorTypeIDEncoding
				discriminator = calculateInstructionDiscriminator(instr.Name)
			}

			for i, b := range discriminator {
				if i > 0 {
					content.WriteString(", ")
				}
				content.WriteString(fmt.Sprintf("%d", b))
			}
			content.WriteString("})\n\n")
		}
	}

	content.WriteString(")\n\n")

	// Generate InstructionIDToName function
	content.WriteString("// InstructionIDToName returns the name of the instruction given its ID.\n")
	content.WriteString("func InstructionIDToName(id ag_binary.TypeID) string {\n")
	content.WriteString("\tswitch id {\n")
	for _, instr := range idl.Instructions() {
		instrName := toCamelCase(instr.Name)
		content.WriteString(fmt.Sprintf("\tcase Instruction_%s:\n", instrName))
		content.WriteString(fmt.Sprintf("\t\treturn \"%s\"\n", instrName))
	}
	content.WriteString("\tdefault:\n")
	content.WriteString("\t\treturn \"\"\n")
	content.WriteString("\t}\n")
	content.WriteString("}\n\n")

	// Generate Instruction struct
	content.WriteString("type Instruction struct {\n")
	content.WriteString("\tag_binary.BaseVariant\n")
	content.WriteString("}\n\n")

	// Generate EncodeToTree method
	content.WriteString("func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {\n")
	content.WriteString("\tif enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {\n")
	content.WriteString("\t\tenToTree.EncodeToTree(parent)\n")
	content.WriteString("\t} else {\n")
	content.WriteString("\t\tparent.Child(ag_spew.Sdump(inst))\n")
	content.WriteString("\t}\n")
	content.WriteString("}\n\n")

	// Generate InstructionImplDef
	content.WriteString("var InstructionImplDef = ag_binary.NewVariantDefinition(\n")

	// Use the appropriate TypeIDEncoding based on the configuration
	switch g.config.TypeID {
	case TypeIDUint8:
		content.WriteString("\tag_binary.Uint8TypeIDEncoding,\n")
	case TypeIDUint32:
		content.WriteString("\tag_binary.Uint32TypeIDEncoding,\n")
	case TypeIDUvarint32:
		content.WriteString("\tag_binary.Uvarint32TypeIDEncoding,\n")
	case TypeIDNoType:
		content.WriteString("\tag_binary.NoTypeIDEncoding,\n")
	default:
		// Default to AnchorTypeIDEncoding
		content.WriteString("\tag_binary.AnchorTypeIDEncoding,\n")
	}

	content.WriteString("\t[]ag_binary.VariantType{\n")
	for _, instr := range idl.Instructions() {
		instrName := toCamelCase(instr.Name)
		snakeName := toSnakeCase(instr.Name)
		content.WriteString(fmt.Sprintf("\t\t{\n\t\t\tName: \"%s\", Type: (*%s)(nil),\n\t\t},\n", snakeName, instrName))
	}
	content.WriteString("\t},\n")
	content.WriteString(")\n\n")

	// Generate ProgramID method
	content.WriteString("func (inst *Instruction) ProgramID() ag_solanago.PublicKey {\n")
	content.WriteString("\treturn ProgramID\n")
	content.WriteString("}\n\n")

	// Generate Accounts method
	content.WriteString("func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {\n")
	content.WriteString("\treturn inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()\n")
	content.WriteString("}\n\n")

	// Generate Data method
	content.WriteString("func (inst *Instruction) Data() ([]byte, error) {\n")
	content.WriteString("\tbuf := new(bytes.Buffer)\n")
	content.WriteString("\tif err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {\n")
	content.WriteString("\t\treturn nil, fmt.Errorf(\"unable to encode instruction: %w\", err)\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn buf.Bytes(), nil\n")
	content.WriteString("}\n\n")

	// Generate TextEncode method
	content.WriteString("func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {\n")
	content.WriteString("\treturn encoder.Encode(inst.Impl, option)\n")
	content.WriteString("}\n\n")

	// Generate UnmarshalWithDecoder method
	content.WriteString("func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {\n")
	content.WriteString("\treturn inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)\n")
	content.WriteString("}\n\n")

	// Generate MarshalWithEncoder method
	content.WriteString("func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {\n")

	// Use the appropriate encoding method based on the configuration
	switch g.config.TypeID {
	case TypeIDUint8:
		content.WriteString("\terr := encoder.WriteUint8(inst.TypeID.Uint8())\n")
	case TypeIDUint32:
		content.WriteString("\terr := encoder.WriteUint32(inst.TypeID.Uint32(), ag_binary.LittleEndian)\n")
	case TypeIDUvarint32:
		content.WriteString("\terr := encoder.WriteUVarInt(inst.TypeID.Uvarint32())\n")
	default:
		// Default to AnchorTypeIDEncoding or other types that use the full bytes
		content.WriteString("\terr := encoder.WriteBytes(inst.TypeID.Bytes(), false)\n")
	}

	content.WriteString("\tif err != nil {\n")
	content.WriteString("\t\treturn fmt.Errorf(\"unable to write variant type: %w\", err)\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn encoder.Encode(inst.Impl)\n")
	content.WriteString("}\n\n")

	// Generate registryDecodeInstruction function
	content.WriteString("func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {\n")
	content.WriteString("\tinst, err := DecodeInstruction(accounts, data)\n")
	content.WriteString("\tif err != nil {\n")
	content.WriteString("\t\treturn nil, err\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn inst, nil\n")
	content.WriteString("}\n\n")

	// Generate DecodeInstruction function
	content.WriteString("func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {\n")
	content.WriteString("\tinst := new(Instruction)\n")
	content.WriteString("\tif err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {\n")
	content.WriteString("\t\treturn nil, fmt.Errorf(\"unable to decode instruction: %w\", err)\n")
	content.WriteString("\t}\n")
	content.WriteString("\tif v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {\n")
	content.WriteString("\t\terr := v.SetAccounts(accounts)\n")
	content.WriteString("\t\tif err != nil {\n")
	content.WriteString("\t\t\treturn nil, fmt.Errorf(\"unable to set accounts for instruction: %w\", err)\n")
	content.WriteString("\t\t}\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn inst, nil\n")
	content.WriteString("}\n\n")

	// Generate DecodeInstructions function
	content.WriteString("func DecodeInstructions(message *ag_solanago.Message) (instructions []*Instruction, err error) {\n")
	content.WriteString("\tfor _, ins := range message.Instructions {\n")
	content.WriteString("\t\tvar programID ag_solanago.PublicKey\n")
	content.WriteString("\t\tif programID, err = message.Program(ins.ProgramIDIndex); err != nil {\n")
	content.WriteString("\t\t\treturn\n")
	content.WriteString("\t\t}\n")
	content.WriteString("\t\tif !programID.Equals(ProgramID) {\n")
	content.WriteString("\t\t\tcontinue\n")
	content.WriteString("\t\t}\n")
	content.WriteString("\t\tvar accounts []*ag_solanago.AccountMeta\n")
	content.WriteString("\t\tif accounts, err = ins.ResolveInstructionAccounts(message); err != nil {\n")
	content.WriteString("\t\t\treturn\n")
	content.WriteString("\t\t}\n")
	content.WriteString("\t\tvar insDecoded *Instruction\n")
	content.WriteString("\t\tif insDecoded, err = DecodeInstruction(accounts, ins.Data); err != nil {\n")
	content.WriteString("\t\t\treturn\n")
	content.WriteString("\t\t}\n")
	content.WriteString("\t\tinstructions = append(instructions, insDecoded)\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn\n")
	content.WriteString("}")

	file.Content = content.Bytes()
	return file, nil
}

// generateInstructionFile generates a file for a single instruction
func (g *InstructionsGenerator) generateInstructionFile(_idl idl.IDL, instr idl.Instruction) (*GeneratedFile, error) {
	instrName := toCamelCase(instr.Name)
	file := &GeneratedFile{
		Name: strings.ToLower(instrName),
		Path: g.config.DstDir,
	}

	var content bytes.Buffer
	content.WriteString("// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.\n\n")
	content.WriteString(fmt.Sprintf("package %s\n\n", g.config.Package))

	// Add imports
	content.WriteString("import (\n")
	content.WriteString("\t\"errors\"\n")
	
	// AIDEV-NOTE: Always include fmt when PDAs exist, goimports will remove if unused
	// Check if any accounts are PDAs (which might use fmt for error formatting)
	hasPDAs := false
	for _, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if ok && account.PDA != nil && len(account.PDA.Seeds) > 0 {
				hasPDAs = true
				break
			}
		}
	}

	if hasPDAs {
		content.WriteString("\t\"fmt\"\n")
	}

	content.WriteString("\tag_binary \"github.com/gagliardetto/binary\"\n")
	content.WriteString("\tag_solanago \"github.com/gagliardetto/solana-go\"\n")
	content.WriteString("\tag_format \"github.com/gagliardetto/solana-go/text/format\"\n")
	content.WriteString("\tag_treeout \"github.com/gagliardetto/treeout\"\n")
	content.WriteString(")\n\n")

	// Generate instruction struct
	content.WriteString(fmt.Sprintf("// %s is the `%s` instruction.\n", instrName, instr.Name))
	content.WriteString(fmt.Sprintf("type %s struct {\n", instrName))

	// Add instruction arguments
	for _, arg := range instr.Args {
		if len(arg.Docs) > 0 {
			for _, doc := range arg.Docs {
				content.WriteString(fmt.Sprintf("\t// %s\n", doc))
			}
		}
		argType := g.generateFieldType(arg.Type, _idl)
		if arg.Optional {
			content.WriteString(fmt.Sprintf("\t%s *%s `bin:\"optional\"`\n", toCamelCase(arg.Name), argType))
		} else {
			content.WriteString(fmt.Sprintf("\t%s *%s\n", toCamelCase(arg.Name), argType))
		}
	}

	// Add account comments
	for i, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}
			content.WriteString(fmt.Sprintf("\n\t// [%d] = [", i))
			if account.Writable {
				content.WriteString("WRITE")
			}
			if account.Signer {
				if account.Writable {
					content.WriteString(", ")
				}
				content.WriteString("SIGNER")
			}
			content.WriteString(fmt.Sprintf("] %s\n", account.Name))
		}
	}

	content.WriteString("\tag_solanago.AccountMetaSlice `bin:\"-\"`\n")
	content.WriteString("}\n\n")

	// Generate builder function
	content.WriteString(fmt.Sprintf("// New%sInstructionBuilder creates a new `%s` instruction builder.\n", instrName, instr.Name))
	content.WriteString(fmt.Sprintf("func New%sInstructionBuilder() *%s {\n", instrName, instrName))
	content.WriteString(fmt.Sprintf("\tnd := &%s{\n", instrName))
	content.WriteString(fmt.Sprintf("\t\tAccountMetaSlice: make(ag_solanago.AccountMetaSlice, %d),\n", len(instr.Accounts)))
	content.WriteString("\t}\n")

	// Set predefined accounts
	for i, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}

			// Check for predefined addresses
			if account.Address != "" {
				content.WriteString(fmt.Sprintf("\tnd.AccountMetaSlice[%d] = ag_solanago.Meta(ag_solanago.MustPublicKeyFromBase58(\"%s\"))", i, account.Address))
				if account.Writable {
					content.WriteString(".WRITE()")
				}
				if account.Signer {
					content.WriteString(".SIGNER()")
				}
				content.WriteString("\n")
			} else if account.Name == "systemProgram" || account.Name == "system_program" {
				content.WriteString(fmt.Sprintf("\tnd.AccountMetaSlice[%d] = ag_solanago.Meta(ag_solanago.MustPublicKeyFromBase58(\"11111111111111111111111111111111\"))\n", i))
			} else if account.Name == "tokenProgram" || account.Name == "token_program" {
				content.WriteString(fmt.Sprintf("\tnd.AccountMetaSlice[%d] = ag_solanago.Meta(ag_solanago.MustPublicKeyFromBase58(\"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA\"))\n", i))
			} else if account.Name == "rent" {
				content.WriteString(fmt.Sprintf("\tnd.AccountMetaSlice[%d] = ag_solanago.Meta(ag_solanago.MustPublicKeyFromBase58(\"SysvarRent111111111111111111111111111111111\"))\n", i))
			}
		}
	}

	content.WriteString("\treturn nd\n")
	content.WriteString("}\n\n")

	// Generate setter methods for arguments
	for _, arg := range instr.Args {
		argName := toCamelCase(arg.Name)
		content.WriteString(fmt.Sprintf("// Set%s sets the \"%s\" parameter.\n", argName, arg.Name))
		content.WriteString(fmt.Sprintf("func (inst *%s) Set%s(%s %s) *%s {\n", instrName, argName, arg.Name, g.generateFieldType(arg.Type, _idl), instrName))
		content.WriteString(fmt.Sprintf("\tinst.%s = &%s\n", argName, arg.Name))
		content.WriteString(fmt.Sprintf("\treturn inst\n"))
		content.WriteString("}\n\n")
	}

	// Generate setter and getter methods for accounts
	for i, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}
			accName := toCamelCase(account.Name)

			// Check if this account is a PDA
			isPDA := account.PDA != nil

			// Setter method
			content.WriteString(fmt.Sprintf("// Set%sAccount sets the \"%s\" account.\n", accName, account.Name))
			content.WriteString(fmt.Sprintf("func (inst *%s) Set%sAccount(%s ag_solanago.PublicKey) *%s {\n", instrName, accName, account.Name, instrName))
			content.WriteString(fmt.Sprintf("\tinst.AccountMetaSlice[%d] = ag_solanago.Meta(%s)", i, account.Name))
			if account.Writable {
				content.WriteString(".WRITE()")
			}
			if account.Signer {
				content.WriteString(".SIGNER()")
			}
			content.WriteString("\n\treturn inst\n")
			content.WriteString("}\n\n")

			// If this is a PDA, generate PDA finding methods
			if isPDA && len(account.PDA.Seeds) > 0 {
				// Generate the internal find method
				content.WriteString(fmt.Sprintf("func (inst *%s) findFind%sAddress(", instrName, accName))

				// Add parameters for each seed
				seedParams := make([]string, 0)
				paramNameCount := make(map[string]int) // Track parameter name occurrences
				uniqueParamNames := make([]string, 0)  // Store unique names in order

				for _, seed := range account.PDA.Seeds {
					if seed.Kind == "account" {
						paramName := seed.Path
						// Handle paths with dots (e.g., "pool.coin_creator")
						if strings.Contains(paramName, ".") {
							paramName = strings.ReplaceAll(paramName, ".", "_")
						}

						// Check if this parameter name has been used before
						if count, exists := paramNameCount[paramName]; exists {
							// Increment count and add suffix
							paramNameCount[paramName] = count + 1
							uniqueParamName := fmt.Sprintf("%s%d", paramName, count+1)
							uniqueParamNames = append(uniqueParamNames, uniqueParamName)
							seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", uniqueParamName))
						} else {
							// First occurrence, no suffix needed
							paramNameCount[paramName] = 1
							uniqueParamNames = append(uniqueParamNames, paramName)
							seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", paramName))
						}
					}
				}

				// AIDEV-NOTE: Add program parameter only if PDA uses account-based program
				// Add program parameter if PDA.Program is specified and is an account (not const)
				// Skip if already present as a seed parameter (dedup)
				if account.PDA.Program != nil && account.PDA.Program.Kind == "account" {
					programParam := account.PDA.Program.Path
					if strings.Contains(programParam, ".") {
						programParam = strings.ReplaceAll(programParam, ".", "_")
					}
					if _, exists := paramNameCount[programParam]; !exists {
						paramNameCount[programParam] = 1
						uniqueParamNames = append(uniqueParamNames, programParam)
						seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", programParam))
					}
				}
				// Note: const program IDs don't need parameters as they're embedded

				// Add knownBumpSeed parameter
				seedParams = append(seedParams, "knownBumpSeed uint8")
				content.WriteString(strings.Join(seedParams, ", "))
				content.WriteString(") (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {\n")

				// Generate seeds array
				content.WriteString("\tvar seeds [][]byte\n")

				// Add each seed using the unique parameter names
				seedIdx := 0
				for _, seed := range account.PDA.Seeds {
					if seed.Kind == "const" {
						// Add constant seed
						content.WriteString("\t// const: ")

						// Try to interpret as UTF-8 string
						constStr := string(seed.Value)
						isPrintable := true
						for _, r := range constStr {
							if !unicode.IsPrint(r) {
								isPrintable = false
								break
							}
						}

						if isPrintable {
							// If it's a printable string, show it
							content.WriteString(fmt.Sprintf("<UTF-8>%s", constStr))
						} else {
							// Otherwise show hex
							content.WriteString("<HEX>")
							for _, b := range seed.Value {
								content.WriteString(fmt.Sprintf("%02x", b))
							}
						}

						content.WriteString("\n\tseeds = append(seeds, []byte{")
						for i, b := range seed.Value {
							if i > 0 {
								content.WriteString(", ")
							}
							content.WriteString(fmt.Sprintf("byte(0x%02x)", b))
						}
						content.WriteString("})\n")
					} else if seed.Kind == "account" {
						// Add account seed
						content.WriteString(fmt.Sprintf("\t// path: %s\n", seed.Path))

						// Use the unique parameter name from the array we built earlier
						uniqueParamName := uniqueParamNames[seedIdx]
						content.WriteString(fmt.Sprintf("\tseeds = append(seeds, %s.Bytes())\n", uniqueParamName))
						seedIdx++
					}
				}

				// AIDEV-NOTE: Handle PDA program field - support both account and const types
				// Determine which program ID to use for PDA derivation
				if account.PDA.Program != nil {
					if account.PDA.Program.Kind == "account" {
						// Use the specified program account
						programParam := account.PDA.Program.Path
						if strings.Contains(programParam, ".") {
							programParam = strings.ReplaceAll(programParam, ".", "_")
						}
						content.WriteString(fmt.Sprintf("\n\t// Using program from account: %s\n", account.PDA.Program.Path))
						content.WriteString("\n\tif knownBumpSeed != 0 {\n")
						content.WriteString("\t\tseeds = append(seeds, []byte{byte(knownBumpSeed)})\n")
						content.WriteString(fmt.Sprintf("\t\tpda, err = ag_solanago.CreateProgramAddress(seeds, %s)\n", programParam))
						content.WriteString("\t} else {\n")
						content.WriteString(fmt.Sprintf("\t\tpda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, %s)\n", programParam))
						content.WriteString("\t}\n")
					} else if account.PDA.Program.Kind == "const" {
						// Use the constant program ID
						content.WriteString("\n\t// Using constant program ID\n")
						content.WriteString("\tprogramID := ag_solanago.PublicKey{\n")
						for i, b := range account.PDA.Program.Value {
							if i%8 == 0 {
								content.WriteString("\t\t")
							}
							content.WriteString(fmt.Sprintf("byte(0x%02x)", b))
							if i < len(account.PDA.Program.Value)-1 {
								content.WriteString(", ")
								if (i+1)%8 == 0 {
									content.WriteString("\n")
								}
							}
						}
						content.WriteString(",\n\t}\n")
						content.WriteString("\n\tif knownBumpSeed != 0 {\n")
						content.WriteString("\t\tseeds = append(seeds, []byte{byte(knownBumpSeed)})\n")
						content.WriteString("\t\tpda, err = ag_solanago.CreateProgramAddress(seeds, programID)\n")
						content.WriteString("\t} else {\n")
						content.WriteString("\t\tpda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)\n")
						content.WriteString("\t}\n")
					}
				} else {
					// Use the default ProgramID
					content.WriteString("\n\t// Using default ProgramID\n")
					content.WriteString("\tif knownBumpSeed != 0 {\n")
					content.WriteString("\t\tseeds = append(seeds, []byte{byte(knownBumpSeed)})\n")
					content.WriteString("\t\tpda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)\n")
					content.WriteString("\t} else {\n")
					content.WriteString("\t\tpda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)\n")
					content.WriteString("\t}\n")
				}
				content.WriteString("\treturn\n")
				content.WriteString("}\n\n")

				// Generate FindWithBumpSeed method
				content.WriteString(fmt.Sprintf("// Find%sAddressWithBumpSeed calculates %s account address with given seeds and a known bump seed.\n", accName, accName))
				content.WriteString(fmt.Sprintf("func (inst *%s) Find%sAddressWithBumpSeed(", instrName, accName))

				// Reuse the unique parameter names from earlier
				seedParams = make([]string, 0)
				seedParamsWithoutType := make([]string, 0)
				for _, uniqueName := range uniqueParamNames {
					seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", uniqueName))
					seedParamsWithoutType = append(seedParamsWithoutType, uniqueName)
				}

				// AIDEV-NOTE: Add program parameter only for account-based PDA programs
				// Add program parameter if PDA.Program is specified and is an account (not const)
				// Skip if already present as a seed parameter (dedup)
				if account.PDA.Program != nil && account.PDA.Program.Kind == "account" {
					programParam := account.PDA.Program.Path
					if strings.Contains(programParam, ".") {
						programParam = strings.ReplaceAll(programParam, ".", "_")
					}
					alreadyPresent := false
					for _, name := range uniqueParamNames {
						if name == programParam {
							alreadyPresent = true
							break
						}
					}
					if !alreadyPresent {
						seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", programParam))
						seedParamsWithoutType = append(seedParamsWithoutType, programParam)
					}
				}
				// Note: const program IDs are embedded directly in the method

				// Add bumpSeed parameter
				seedParams = append(seedParams, "bumpSeed uint8")
				seedParamsWithoutType = append(seedParamsWithoutType, "bumpSeed")
				content.WriteString(strings.Join(seedParams, ", "))
				content.WriteString(") (pda ag_solanago.PublicKey, err error) {\n")
				content.WriteString(fmt.Sprintf("\tpda, _, err = inst.findFind%sAddress(%s)\n", accName, strings.Join(seedParamsWithoutType, ", ")))
				content.WriteString("\treturn\n")
				content.WriteString("}\n\n")

				// Generate MustFindWithBumpSeed method
				content.WriteString(fmt.Sprintf("func (inst *%s) MustFind%sAddressWithBumpSeed(", instrName, accName))
				content.WriteString(strings.Join(seedParams, ", "))
				content.WriteString(") (pda ag_solanago.PublicKey) {\n")
				content.WriteString(fmt.Sprintf("\tpda, _, err := inst.findFind%sAddress(%s)\n", accName, strings.Join(seedParamsWithoutType, ", ")))
				content.WriteString("\tif err != nil {\n")
				content.WriteString("\t\tpanic(err)\n")
				content.WriteString("\t}\n")
				content.WriteString("\treturn\n")
				content.WriteString("}\n\n")

				// Generate Find method
				content.WriteString(fmt.Sprintf("// Find%sAddress finds %s account address with given seeds.\n", accName, accName))

				// Reuse the unique parameter names for Find method too
				seedParams = make([]string, 0)
				seedParamsWithoutType = make([]string, 0)
				for _, uniqueName := range uniqueParamNames {
					seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", uniqueName))
					seedParamsWithoutType = append(seedParamsWithoutType, uniqueName)
				}

				// AIDEV-NOTE: Add program parameter for Find methods (account-based only)
				// Add program parameter if PDA.Program is specified and is an account (not const)
				// Skip if already present as a seed parameter (dedup)
				if account.PDA.Program != nil && account.PDA.Program.Kind == "account" {
					programParam := account.PDA.Program.Path
					if strings.Contains(programParam, ".") {
						programParam = strings.ReplaceAll(programParam, ".", "_")
					}
					alreadyPresent := false
					for _, name := range uniqueParamNames {
						if name == programParam {
							alreadyPresent = true
							break
						}
					}
					if !alreadyPresent {
						seedParams = append(seedParams, fmt.Sprintf("%s ag_solanago.PublicKey", programParam))
						seedParamsWithoutType = append(seedParamsWithoutType, programParam)
					}
				}
				// Note: const program IDs are embedded directly in the method

				content.WriteString(fmt.Sprintf("func (inst *%s) Find%sAddress(", instrName, accName))
				content.WriteString(strings.Join(seedParams, ", "))
				content.WriteString(") (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {\n")

				// AIDEV-NOTE: Pass all parameters including program if specified
				// Handle the case where there are no account seeds
				allParams := make([]string, 0)
				allParams = append(allParams, seedParamsWithoutType...)
				allParams = append(allParams, "0") // bump seed
				content.WriteString(fmt.Sprintf("\tpda, bumpSeed, err = inst.findFind%sAddress(%s)\n", accName, strings.Join(allParams, ", ")))

				content.WriteString("\treturn\n")
				content.WriteString("}\n\n")

				// Generate MustFind method
				content.WriteString(fmt.Sprintf("func (inst *%s) MustFind%sAddress(", instrName, accName))
				content.WriteString(strings.Join(seedParams, ", "))
				content.WriteString(") (pda ag_solanago.PublicKey) {\n")

				// AIDEV-NOTE: Pass all parameters including program if specified for MustFind too
				// Handle the case where there are no account seeds
				allParams2 := make([]string, 0)
				allParams2 = append(allParams2, seedParamsWithoutType...)
				allParams2 = append(allParams2, "0") // bump seed
				content.WriteString(fmt.Sprintf("\tpda, _, err := inst.findFind%sAddress(%s)\n", accName, strings.Join(allParams2, ", ")))

				content.WriteString("\tif err != nil {\n")
				content.WriteString("\t\tpanic(err)\n")
				content.WriteString("\t}\n")
				content.WriteString("\treturn\n")
				content.WriteString("}\n\n")
			}

			// Getter method
			content.WriteString(fmt.Sprintf("// Get%sAccount gets the \"%s\" account.\n", accName, account.Name))
			content.WriteString(fmt.Sprintf("func (inst *%s) Get%sAccount() *ag_solanago.AccountMeta {\n", instrName, accName))
			content.WriteString(fmt.Sprintf("\treturn inst.AccountMetaSlice.Get(%d)\n", i))
			content.WriteString("}\n\n")
		}
	}

	// Generate Build method
	content.WriteString(fmt.Sprintf("func (inst %s) Build() *Instruction {\n", instrName))
	content.WriteString("\treturn &Instruction{BaseVariant: ag_binary.BaseVariant{\n")
	content.WriteString("\t\tImpl:   inst,\n")
	content.WriteString(fmt.Sprintf("\t\tTypeID: Instruction_%s,\n", instrName))
	content.WriteString("\t}}\n")
	content.WriteString("}\n\n")

	// Generate ValidateAndBuild method
	content.WriteString("// ValidateAndBuild validates the instruction parameters and accounts;\n")
	content.WriteString("// if there is a validation error, it returns the error.\n")
	content.WriteString("// Otherwise, it builds and returns the instruction.\n")
	content.WriteString(fmt.Sprintf("func (inst %s) ValidateAndBuild() (*Instruction, error) {\n", instrName))
	content.WriteString("\tif err := inst.Validate(); err != nil {\n")
	content.WriteString("\t\treturn nil, err\n")
	content.WriteString("\t}\n")
	content.WriteString("\treturn inst.Build(), nil\n")
	content.WriteString("}\n\n")

	// Generate Validate method
	content.WriteString(fmt.Sprintf("func (inst *%s) Validate() error {\n", instrName))

	// Validate arguments
	if len(instr.Args) > 0 {
		content.WriteString("\t// Check whether all (required) parameters are set:\n")
		content.WriteString("\t{\n")
		for _, arg := range instr.Args {
			if !arg.Optional {
				argName := toCamelCase(arg.Name)
				content.WriteString(fmt.Sprintf("\t\tif inst.%s == nil {\n", argName))
				content.WriteString(fmt.Sprintf("\t\t\treturn errors.New(\"%s parameter is not set\")\n", argName))
				content.WriteString("\t\t}\n")
			}
		}
		content.WriteString("\t}\n")
	}

	// Validate accounts
	content.WriteString("\t// Check whether all (required) accounts are set:\n")
	content.WriteString("\t{\n")
	for i, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}
			if !account.Optional {
				accName := toCamelCase(account.Name)
				content.WriteString(fmt.Sprintf("\t\tif inst.AccountMetaSlice[%d] == nil {\n", i))
				content.WriteString(fmt.Sprintf("\t\t\treturn errors.New(\"accounts.%s is not set\")\n", accName))
				content.WriteString("\t\t}\n")
			}
		}
	}
	content.WriteString("\t}\n")
	content.WriteString("\treturn nil\n")
	content.WriteString("}\n\n")

	// Generate EncodeToTree method
	content.WriteString(fmt.Sprintf("func (inst *%s) EncodeToTree(parent ag_treeout.Branches) {\n", instrName))
	content.WriteString("\tparent.Child(ag_format.Program(ProgramName, ProgramID)).\n")
	content.WriteString("\t\t//\n")
	content.WriteString("\t\tParentFunc(func(programBranch ag_treeout.Branches) {\n")
	content.WriteString(fmt.Sprintf("\t\t\tprogramBranch.Child(ag_format.Instruction(\"%s\")).\n", instrName))
	content.WriteString("\t\t\t\t//\n")
	content.WriteString("\t\t\t\tParentFunc(func(instructionBranch ag_treeout.Branches) {\n\n")

	// Parameters section
	content.WriteString("\t\t\t\t\t// Parameters of the instruction:\n")
	content.WriteString(fmt.Sprintf("\t\t\t\t\tinstructionBranch.Child(\"Params[len=%d]\").ParentFunc(func(paramsBranch ag_treeout.Branches) {\n", len(instr.Args)))
	for _, arg := range instr.Args {
		argName := toCamelCase(arg.Name)
		content.WriteString(fmt.Sprintf("\t\t\t\t\t\tparamsBranch.Child(ag_format.Param(\"%s\", inst.%s))\n", arg.Name, argName))
	}
	content.WriteString("\t\t\t\t\t})\n\n")

	// Accounts section
	content.WriteString("\t\t\t\t\t// Accounts of the instruction:\n")
	content.WriteString(fmt.Sprintf("\t\t\t\t\tinstructionBranch.Child(\"Accounts[len=%d]\").ParentFunc(func(accountsBranch ag_treeout.Branches) {\n", len(instr.Accounts)))
	for i, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}
			content.WriteString(fmt.Sprintf("\t\t\t\t\t\taccountsBranch.Child(ag_format.Meta(\"%s\", inst.AccountMetaSlice.Get(%d)))\n", account.Name, i))
		}
	}
	content.WriteString("\t\t\t\t\t})\n")
	content.WriteString("\t\t\t\t})\n")
	content.WriteString("\t\t})\n")
	content.WriteString("}\n\n")

	// Generate MarshalWithEncoder method
	content.WriteString(fmt.Sprintf("func (obj %s) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {\n", instrName))

	// Add serialization code for each argument
	for _, arg := range instr.Args {
		argName := toCamelCase(arg.Name)
		content.WriteString(fmt.Sprintf("\t// Serialize `%s` param:\n", argName))
		if arg.Type.IsOption() {
			// Borsh option: write 1-byte discriminator, then payload only when Some.
			content.WriteString(fmt.Sprintf("\tif obj.%s == nil {\n", argName))
			content.WriteString("\t\terr = encoder.WriteByte(0)\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t} else {\n")
			content.WriteString("\t\terr = encoder.WriteByte(1)\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString(fmt.Sprintf("\t\terr = encoder.Encode(obj.%s)\n", argName))
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t}\n")
		} else if arg.Optional {
			// AIDEV-NOTE: Fixed optional field encoding - write presence flag first
			content.WriteString(fmt.Sprintf("\tif obj.%s != nil {\n", argName))
			content.WriteString("\t\terr = encoder.WriteBool(true)\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString(fmt.Sprintf("\t\terr = encoder.Encode(*obj.%s)\n", argName))
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t} else {\n")
			content.WriteString("\t\terr = encoder.WriteBool(false)\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t}\n")
		} else {
			content.WriteString(fmt.Sprintf("\terr = encoder.Encode(obj.%s)\n", argName))
			content.WriteString("\tif err != nil {\n")
			content.WriteString("\t\treturn err\n")
			content.WriteString("\t}\n")
		}
	}

	content.WriteString("\treturn nil\n")
	content.WriteString("}\n")

	// Generate UnmarshalWithDecoder method
	content.WriteString(fmt.Sprintf("func (obj *%s) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {\n", instrName))

	// Add deserialization code for each argument
	for _, arg := range instr.Args {
		argName := toCamelCase(arg.Name)
		content.WriteString(fmt.Sprintf("\t// Deserialize `%s`:\n", argName))
		// AIDEV-NOTE: Always check decoder.Remaining() to prevent panics when fields are missing
		content.WriteString("\tif decoder.Remaining() > 0 {\n")
		if arg.Type.IsOption() {
			// Borsh option: read 1-byte discriminator, then decode payload only when Some.
			innerType := g.generateFieldType(arg.Type.(*types.OptionType).ElementType, _idl)
			content.WriteString("\t\toptTag, err := decoder.ReadByte()\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t\tif optTag == 1 {\n")
			content.WriteString(fmt.Sprintf("\t\t\tvar v %s\n", innerType))
			content.WriteString("\t\t\tif err := decoder.Decode(&v); err != nil {\n")
			content.WriteString("\t\t\t\treturn err\n")
			content.WriteString("\t\t\t}\n")
			content.WriteString(fmt.Sprintf("\t\t\tobj.%s = &v\n", argName))
			content.WriteString("\t\t} else {\n")
			content.WriteString(fmt.Sprintf("\t\t\tobj.%s = nil\n", argName))
			content.WriteString("\t\t}\n")
		} else if arg.Optional {
			content.WriteString("\t\tok, err := decoder.ReadBool()\n")
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
			content.WriteString("\t\tif ok {\n")
			argType := g.generateFieldType(arg.Type, _idl)
			content.WriteString(fmt.Sprintf("\t\t\ttmp := new(%s)\n", argType))
			content.WriteString("\t\t\terr = decoder.Decode(tmp)\n")
			content.WriteString("\t\t\tif err != nil {\n")
			content.WriteString("\t\t\t\treturn err\n")
			content.WriteString("\t\t\t}\n")
			content.WriteString(fmt.Sprintf("\t\t\tobj.%s = tmp\n", argName))
			content.WriteString("\t\t}\n")
		} else {
			content.WriteString(fmt.Sprintf("\t\terr = decoder.Decode(&obj.%s)\n", argName))
			content.WriteString("\t\tif err != nil {\n")
			content.WriteString("\t\t\treturn err\n")
			content.WriteString("\t\t}\n")
		}
		content.WriteString("\t}\n")
	}

	content.WriteString("\treturn nil\n")
	content.WriteString("}\n\n")

	// Generate NewInstruction function
	content.WriteString(fmt.Sprintf("// New%sInstruction declares a new %s instruction with the provided parameters and accounts.\n", instrName, instrName))
	content.WriteString(fmt.Sprintf("func New%sInstruction(\n", instrName))
	content.WriteString("\t// Parameters:\n")

	// Generate argument parameters
	for i, arg := range instr.Args {
		argType := g.generateFieldType(arg.Type, _idl)
		content.WriteString(fmt.Sprintf("\t%s %s", arg.Name, argType))
		if i < len(instr.Args)-1 || len(instr.Accounts) > 0 {
			content.WriteString(",\n")
		}
	}

	content.WriteString("\t// Accounts:\n")

	// Generate account parameters (only for non-system and non-PDA accounts)
	requiredAccounts := make([]idl.AccountItem, 0)

	// Track if we need additional parameters for PDA seeds
	additionalParams := make(map[string]bool)

	// First pass: identify accounts and additional parameters needed for PDAs
	for _, acc := range instr.Accounts {
		if acc.IsAccount() {
			account, ok := acc.(*idl.Account)
			if !ok {
				continue
			}

			// Skip system accounts
			if account.Address != "" ||
				account.Name == "systemProgram" || account.Name == "system_program" ||
				account.Name == "tokenProgram" || account.Name == "token_program" ||
				account.Name == "rent" {
				continue
			}

			// If this is a PDA, check if we need additional parameters
			if account.PDA != nil {
				for _, seed := range account.PDA.Seeds {
					if seed.Kind == "account" && strings.Contains(seed.Path, ".") {
						paramName := strings.ReplaceAll(seed.Path, ".", "_")
						additionalParams[paramName] = true
					}
				}
				// AIDEV-NOTE: Add program parameter if PDA uses external program
				// Check if this PDA uses an external program
				if account.PDA.Program != nil && account.PDA.Program.Kind == "account" {
					programParam := account.PDA.Program.Path
					if strings.Contains(programParam, ".") {
						programParam = strings.ReplaceAll(programParam, ".", "_")
					}
					// Only add if not already a required account
					isRequiredAccount := false
					for _, reqAcc := range requiredAccounts {
						if reqAccount, ok := reqAcc.(*idl.Account); ok && reqAccount.Name == programParam {
							isRequiredAccount = true
							break
						}
					}
					if !isRequiredAccount {
						additionalParams[programParam] = true
					}
				}
				continue
			}

			requiredAccounts = append(requiredAccounts, account)
		}
	}

	// Add regular account parameters
	for _, acc := range requiredAccounts {
		account := acc.(*idl.Account)
		content.WriteString(fmt.Sprintf("\t%s ag_solanago.PublicKey", account.Name))
		content.WriteString(",\n")
	}

	// Add additional parameters for PDA seeds
	additionalParamsList := make([]string, 0, len(additionalParams))
	for param := range additionalParams {
		additionalParamsList = append(additionalParamsList, param)
	}
	sort.Strings(additionalParamsList) // Sort for consistent output

	for i, param := range additionalParamsList {
		content.WriteString(fmt.Sprintf("\t%s ag_solanago.PublicKey", param))
		if i < len(additionalParamsList)-1 || i == len(additionalParamsList)-1 {
			content.WriteString(",\n")
		}
	}

	// Close the parameter list
	content.WriteString(fmt.Sprintf(") (*%s, error) {\n", instrName))

	// Generate builder call
	content.WriteString(fmt.Sprintf("\tnd := New%sInstructionBuilder()\n", instrName))

	// Set arguments
	for _, arg := range instr.Args {
		argName := toCamelCase(arg.Name)
		content.WriteString(fmt.Sprintf("\tnd.Set%s(%s)\n", argName, arg.Name))
	}

	// Set required accounts
	for _, acc := range requiredAccounts {
		account := acc.(*idl.Account)
		accName := toCamelCase(account.Name)
		content.WriteString(fmt.Sprintf("\tnd.Set%sAccount(%s)\n", accName, account.Name))
	}

	// Calculate and set PDAs
	if err := g.generatePDACalculations(&content, instr, requiredAccounts, additionalParams); err != nil {
		return nil, err
	}

	content.WriteString("\treturn nd, nil\n")
	content.WriteString("}")

	file.Content = content.Bytes()
	return file, nil
}

// generateFieldType generates Go type for an IDL type
func (g *InstructionsGenerator) generateFieldType(t idl.Type, _idl idl.IDL) string {
	if t.IsBasic() {
		// Map basic types to Go types
		typeName := t.String()

		// Handle array and option types from the parser
		if strings.HasPrefix(typeName, "array:") {
			elemType := strings.TrimPrefix(typeName, "array:")
			return fmt.Sprintf("[]%s", g.mapBasicType(elemType))
		} else if strings.HasPrefix(typeName, "option:") {
			elemType := strings.TrimPrefix(typeName, "option:")
			return fmt.Sprintf("*%s", g.mapBasicType(elemType))
		}

		return g.mapBasicType(typeName)
	} else if t.IsArray() {
		// Handle array types
		arrayType := t.(interface {
			ElementType() idl.Type
			Size() int
		})
		elemType := g.generateFieldType(arrayType.ElementType(), _idl)
		return fmt.Sprintf("[%d]%s", arrayType.Size(), elemType)
	} else if t.IsVector() {
		// Handle vector types
		vecType, ok := t.(*types.VectorType)
		if !ok {
			return "interface{}"
		}
		elemType := g.generateFieldType(vecType.ElementType, _idl)
		return fmt.Sprintf("[]%s", elemType)
	} else if t.IsOption() {
		// Handle option types
		optType, ok := t.(*types.OptionType)
		if !ok {
			return "interface{}"
		}
		elemType := g.generateFieldType(optType.ElementType, _idl)
		return fmt.Sprintf("*%s", elemType)
	} else if t.IsDefined() {
		// Handle defined types
		typeName := t.String()

		// Check if this type is an account type in the IDL
		for _, account := range _idl.Accounts() {
			if account.Name == typeName {
				// If it's an account type, append "Account" suffix
				return typeName + "Account"
			}
		}

		return typeName
	}

	return "interface{}"
}

// mapBasicType maps basic IDL types to Go types
func (g *InstructionsGenerator) mapBasicType(typeName string) string {
	switch typeName {
	case "bool":
		return "bool"
	case "u8":
		return "uint8"
	case "i8":
		return "int8"
	case "u16":
		return "uint16"
	case "i16":
		return "int16"
	case "u32":
		return "uint32"
	case "i32":
		return "int32"
	case "u64":
		return "uint64"
	case "i64":
		return "int64"
	case "u128":
		return "ag_binary.Uint128"
	case "i128":
		return "ag_binary.Int128"
	case "bytes":
		return "[]byte"
	case "string":
		return "string"
	case "publicKey", "pubkey":
		return "ag_solanago.PublicKey"
	case "f32":
		return "float32"
	case "f64":
		return "float64"
	case "unixTimestamp":
		return "ag_solanago.UnixTimeSeconds"
	case "hash":
		return "ag_solanago.Hash"
	case "duration":
		return "ag_solanago.DurationSeconds"
	default:
		return "interface{}"
	}
}

// toSnakeCase converts a string to snake_case
func toSnakeCase(s string) string {
	// AIDEV-NOTE: Fixed to use proper snake_case conversion for variant names
	// This must match the snake_case used in discriminator calculation
	return sighash.ToSnakeForSighash(s)
}
