package generator

import (
	"fmt"

	"github.com/iamrekas/anchor-go/pkg/idl"
	"github.com/iamrekas/anchor-go/pkg/idl/types"
)

// OptionalGenerator emits an Optional[T] generic wrapper type into the
// generated package whenever the IDL contains at least one option<T>. The
// wrapper owns its own Borsh discriminator handling, which lets the other
// generators stop emitting per-call-site option logic.
type OptionalGenerator struct {
	config *Config
}

// NewOptionalGenerator creates a new OptionalGenerator.
func NewOptionalGenerator() *OptionalGenerator {
	return &OptionalGenerator{config: DefaultConfig()}
}

// Generate implements Generator.Generate.
func (g *OptionalGenerator) Generate(_idl idl.IDL) ([]*GeneratedFile, error) {
	if !idlUsesOption(_idl) {
		return nil, nil
	}

	content := fmt.Sprintf("// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.\n\npackage %s\n\n", g.config.Package)
	content += `import (
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
)

// Optional is a Borsh option<T>. Set=false marshals as the single byte 0x00;
// Set=true marshals as 0x01 followed by the Borsh encoding of Value. The
// wrapper implements ag_binary.BinaryMarshaler / BinaryUnmarshaler so it is
// dispatched automatically by the reflective Encode / Decode path.
type Optional[T any] struct {
	Set   bool
	Value T
}

// Some returns an Optional[T] holding v.
func Some[T any](v T) Optional[T] { return Optional[T]{Set: true, Value: v} }

// None returns an empty Optional[T].
func None[T any]() Optional[T] { return Optional[T]{} }

// MarshalWithEncoder writes the Borsh option discriminator and (when set) the payload.
func (o Optional[T]) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	if !o.Set {
		return encoder.WriteByte(0)
	}
	if err := encoder.WriteByte(1); err != nil {
		return err
	}
	return encoder.Encode(o.Value)
}

// UnmarshalWithDecoder reads the Borsh option discriminator and (when set) the payload.
func (o *Optional[T]) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	tag, err := decoder.ReadByte()
	if err != nil {
		return err
	}
	switch tag {
	case 0:
		var zero T
		o.Set = false
		o.Value = zero
		return nil
	case 1:
		o.Set = true
		return decoder.Decode(&o.Value)
	default:
		return fmt.Errorf("invalid borsh option tag: %d", tag)
	}
}

// String renders the option for debug output.
func (o Optional[T]) String() string {
	if !o.Set {
		return "None"
	}
	return fmt.Sprintf("Some(%v)", o.Value)
}
`

	return []*GeneratedFile{{
		Name:    "optional",
		Content: []byte(content),
		Path:    g.config.DstDir,
	}}, nil
}

// SetConfig implements Generator.SetConfig.
func (g *OptionalGenerator) SetConfig(config *Config) { g.config = config }

// GetConfig implements Generator.GetConfig.
func (g *OptionalGenerator) GetConfig() *Config { return g.config }

// idlUsesOption reports whether any field, account field, event field, or
// instruction arg in the IDL is of option<T> kind. Walks one level of array /
// vector / option nesting to catch composites like option<vec<u8>>.
func idlUsesOption(_idl idl.IDL) bool {
	for _, td := range _idl.Types() {
		for _, f := range td.Fields {
			if typeUsesOption(f.Type) {
				return true
			}
		}
		for _, v := range td.Variants {
			for _, f := range v.Fields {
				if typeUsesOption(f.Type) {
					return true
				}
			}
		}
	}
	for _, a := range _idl.Accounts() {
		for _, f := range a.Type.Fields {
			if typeUsesOption(f.Type) {
				return true
			}
		}
	}
	for _, e := range _idl.Events() {
		for _, f := range e.Fields {
			if typeUsesOption(f.Type) {
				return true
			}
		}
	}
	for _, instr := range _idl.Instructions() {
		for _, a := range instr.Args {
			if typeUsesOption(a.Type) {
				return true
			}
		}
	}
	return false
}

// typeUsesOption reports whether t is option<...> or contains one as an
// immediate element type. Recurses through option, vec, array so that
// option<vec<u8>>, vec<option<u8>>, [N]option<u8>, etc. are all detected.
func typeUsesOption(t idl.Type) bool {
	if t == nil {
		return false
	}
	if t.IsOption() {
		return true
	}
	if t.IsBasic() {
		// Parser may encode option<basic> as the string "option:T"; the
		// per-generator generateFieldType handles this form, so flag it here.
		s := t.String()
		if len(s) >= 7 && s[:7] == "option:" {
			return true
		}
		return false
	}
	switch tt := t.(type) {
	case *types.OptionType:
		return true
	case *types.VectorType:
		return typeUsesOption(tt.ElementType)
	case *types.ArrayType:
		return typeUsesOption(tt.ElemType)
	}
	return false
}
