package generator

import (
	"fmt"
	"strings"

	"github.com/iamrekas/anchor-go/pkg/idl"
	"github.com/iamrekas/anchor-go/pkg/idl/types"
)

// TypesGenerator generates code for custom types
type TypesGenerator struct {
	config *Config
}

// NewTypesGenerator creates a new types generator
func NewTypesGenerator() *TypesGenerator {
	return &TypesGenerator{
		config: DefaultConfig(),
	}
}

// Generate implements Generator.Generate
func (g *TypesGenerator) Generate(_idl idl.IDL) ([]*GeneratedFile, error) {
	if len(_idl.Types()) == 0 {
		// No types to generate
		return nil, nil
	}

	// Create a file for types
	file := &GeneratedFile{
		Name: "types",
		Path: g.config.DstDir,
	}

	// Generate code for each type
	var content string
	content += fmt.Sprintf("// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.\n\n")
	content += fmt.Sprintf("package %s\n\n", g.config.Package)

	// Add imports
	content += "import (\n"

	// Check if any type has a discriminator or error handling that would require fmt
	needsFmt := false
	for _, typeDef := range _idl.Types() {
		if typeDef.Discriminator != nil || typeDef.Kind == idl.TypeDefKindEnum {
			needsFmt = true
			break
		}
	}

	if needsFmt {
		content += "\t\"fmt\"\n"
	}

	content += "\tag_binary \"github.com/gagliardetto/binary\"\n"

	// Check if any type uses solana.PublicKey
	needsSolana := false
	for _, typeDef := range _idl.Types() {
		if typeDef.Kind == idl.TypeDefKindStruct {
			for _, field := range typeDef.Fields {
				if field.Type.IsBasic() && (field.Type.String() == "publicKey" || field.Type.String() == "pubkey") {
					needsSolana = true
					break
				}
			}
		}
		if needsSolana {
			break
		}
	}

	if needsSolana {
		content += "\tag_solanago \"github.com/gagliardetto/solana-go\"\n"
	}

	content += ")\n\n"

	// First, generate all the struct types
	for _, typeDef := range _idl.Types() {
		if typeDef.Kind == idl.TypeDefKindStruct {
			content += g.generateType(typeDef)
		}
	}

	// Then, generate all the interface types for enums
	for _, typeDef := range _idl.Types() {
		if typeDef.Kind == idl.TypeDefKindEnum {
			// Generate interface type
			if strings.HasPrefix(typeDef.Name, "Versioned") || typeDef.Name == "InstructionRequest" {
				content += fmt.Sprintf("type %s interface {\n", typeDef.Name)
				content += fmt.Sprintf("\tis%s()\n", typeDef.Name)
				content += "}\n\n"

				// Generate container type for serialization/deserialization
				content += fmt.Sprintf("type %sContainer struct {\n", strings.ToLower(typeDef.Name))
				content += fmt.Sprintf("\tEnum ag_binary.BorshEnum `borsh_enum:\"true\"`\n")
				for _, variant := range typeDef.Variants {
					content += fmt.Sprintf("\t%s %s%sTuple\n", variant.Name, typeDef.Name, variant.Name)
				}
				content += "}\n\n"

				// Generate tuple types for each variant
				for _, variant := range typeDef.Variants {
					content += fmt.Sprintf("type %s%sTuple struct {\n", typeDef.Name, variant.Name)
					if len(variant.Fields) > 0 {
						// For variants with fields, we'll create a tuple with the fields
						for i, field := range variant.Fields {
							fieldType := g.generateFieldType(field.Type)
							content += fmt.Sprintf("\tElem%d %s\n", i, fieldType)
						}
					} else {
						// For variants without fields, we'll create an empty tuple
						content += fmt.Sprintf("\t// Empty tuple\n")
					}
					content += "}\n\n"

					// Add the is<Interface> method to implement the interface
					content += fmt.Sprintf("func (_ %s%sTuple) is%s() {}\n\n", typeDef.Name, variant.Name, typeDef.Name)
				}
			} else {
				content += g.generateType(typeDef)
			}
		}
	}

	// Finally, generate all the alias types
	for _, typeDef := range _idl.Types() {
		if typeDef.Kind == idl.TypeDefKindAlias {
			content += g.generateType(typeDef)
		}
	}

	file.Content = []byte(content)
	return []*GeneratedFile{file}, nil
}

// SetConfig implements Generator.SetConfig
func (g *TypesGenerator) SetConfig(config *Config) {
	g.config = config
}

// GetConfig implements Generator.GetConfig
func (g *TypesGenerator) GetConfig() *Config {
	return g.config
}

// generateType generates code for a single type
func (g *TypesGenerator) generateType(typeDef idl.TypeDef) string {
	var code string

	// Add documentation
	if len(typeDef.Docs) > 0 {
		code += "// " + typeDef.Name + " represents a custom type\n"
		for _, doc := range typeDef.Docs {
			// Split multi-line comments by newline and add // prefix to each line
			lines := strings.Split(doc, "\n")
			for _, line := range lines {
				code += "// " + line + "\n"
			}
		}
	} else {
		code += "// " + typeDef.Name + " represents a custom type\n"
	}

	// Generate code based on the type kind
	switch typeDef.Kind {
	case idl.TypeDefKindStruct:
		code += g.generateStruct(typeDef)
	case idl.TypeDefKindEnum:
		code += g.generateEnum(typeDef)
	case idl.TypeDefKindAlias:
		code += g.generateAlias(typeDef)
	}

	return code
}

// isComplexEnum checks if a field type is a complex enum
func (g *TypesGenerator) isComplexEnum(t idl.Type) bool {
	if t.IsDefined() {
		typeName := t.String()
		return strings.HasPrefix(typeName, "Versioned") || typeName == "InstructionRequest"
	}
	return false
}

// generateStruct generates code for a struct type
func (g *TypesGenerator) generateStruct(typeDef idl.TypeDef) string {
	var code string

	// Generate struct definition
	code += fmt.Sprintf("type %s struct {\n", typeDef.Name)

	// Track used field names to handle duplicates
	// AIDEV-NOTE: Deduplicate field names by adding suffix when conflicts occur
	usedFieldNames := make(map[string]int)

	// Generate fields
	for _, field := range typeDef.Fields {
		if len(field.Docs) > 0 {
			for _, doc := range field.Docs {
				code += "\t// " + doc + "\n"
			}
		}

		// Generate field with type
		fieldType := g.generateFieldType(field.Type)
		// Capitalize the first letter of the field name to make it public
		baseFieldName := toCamelCase(field.Name)
		
		// Handle duplicate field names
		fieldName := baseFieldName
		if count, exists := usedFieldNames[baseFieldName]; exists {
			// Add suffix for duplicate field names
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			usedFieldNames[baseFieldName] = count + 1
		} else {
			usedFieldNames[baseFieldName] = 1
		}

		// option<T> and IDL "optional: true" both render as Optional[T] (a
		// self-contained Borsh marshaler). generateFieldType already returns
		// Optional[T] for option<T>; for the IDL flag on a non-option type we
		// wrap here. The reflective bin:"optional" tag is unused because our
		// MarshalWithEncoder body bypasses ag_binary's struct walk.
		if field.Optional && !field.Type.IsOption() {
			code += fmt.Sprintf("\t%s Optional[%s]\n", fieldName, fieldType)
		} else {
			code += fmt.Sprintf("\t%s %s\n", fieldName, fieldType)
		}
	}

	code += "}\n\n"

	// Generate discriminator constant if available
	if typeDef.Discriminator != nil {
		code += fmt.Sprintf("// %sDiscriminator is the discriminator for the %s type\n", typeDef.Name, typeDef.Name)
		code += fmt.Sprintf("var %sDiscriminator = [8]byte{", typeDef.Name)
		for i, b := range typeDef.Discriminator {
			if i > 0 {
				code += ", "
			}
			code += fmt.Sprintf("%d", b)
		}
		code += "}\n\n"
	}

	// Generate MarshalWithEncoder method
	code += fmt.Sprintf("func (obj %s) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {\n", typeDef.Name)
	if typeDef.Discriminator != nil {
		code += fmt.Sprintf("\t// Write type discriminator\n")
		code += fmt.Sprintf("\tif err := encoder.WriteBytes(%sDiscriminator[:], false); err != nil {\n", typeDef.Name)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to write discriminator: %%w\", err)\n")
		code += fmt.Sprintf("\t}\n\n")
	}

	// Track used field names again for marshal method
	// AIDEV-NOTE: Need to regenerate deduplicated names for marshal/unmarshal methods
	marshalUsedNames := make(map[string]int)

	// Marshal fields
	for _, field := range typeDef.Fields {
		baseFieldName := toCamelCase(field.Name)
		
		// Handle duplicate field names (same logic as struct generation)
		fieldName := baseFieldName
		if count, exists := marshalUsedNames[baseFieldName]; exists {
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			marshalUsedNames[baseFieldName] = count + 1
		} else {
			marshalUsedNames[baseFieldName] = 1
		}

		// Check if the field is a complex enum
		if g.isComplexEnum(field.Type) {
			typeName := field.Type.String()
			code += fmt.Sprintf("\t// Serialize `%s` param:\n", field.Name)
			code += fmt.Sprintf("\t{\n")
			code += fmt.Sprintf("\t\ttmp := %sContainer{}\n", strings.ToLower(typeName))
			code += fmt.Sprintf("\t\tswitch realvalue := obj.%s.(type) {\n", fieldName)

			// Get the variants for this enum type
			for i, variant := range typeDef.Variants {
				variantName := variant.Name
				code += fmt.Sprintf("\t\tcase *%s%sTuple:\n", typeName, variantName)
				code += fmt.Sprintf("\t\t\ttmp.Enum = %d\n", i)
				code += fmt.Sprintf("\t\t\ttmp.%s = *realvalue\n", variantName)
			}

			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t\terr := encoder.Encode(tmp)\n")
			code += fmt.Sprintf("\t\tif err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn err\n")
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t}\n")
		} else {
			// option<T> and "optional: true" both arrive as Optional[T] from the
			// field declaration; the wrapper self-marshals.
			code += fmt.Sprintf("\t// Serialize `%s` param:\n", field.Name)
			code += fmt.Sprintf("\terr = encoder.Encode(obj.%s)\n", fieldName)
			code += fmt.Sprintf("\tif err != nil {\n")
			code += fmt.Sprintf("\t\treturn err\n")
			code += fmt.Sprintf("\t}\n")
		}
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	// Generate UnmarshalWithDecoder method
	code += fmt.Sprintf("func (obj *%s) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {\n", typeDef.Name)
	if typeDef.Discriminator != nil {
		code += fmt.Sprintf("\t// Read and verify type discriminator\n")
		code += fmt.Sprintf("\tdiscriminator, err := decoder.ReadTypeID()\n")
		code += fmt.Sprintf("\tif err != nil {\n")
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to read discriminator: %%w\", err)\n")
		code += fmt.Sprintf("\t}\n")
		code += fmt.Sprintf("\tif !discriminator.Equal(%sDiscriminator[:]) {\n", typeDef.Name)
		code += fmt.Sprintf("\t\treturn fmt.Errorf(\"invalid discriminator: expected %%v, got %%v\", %sDiscriminator[:], discriminator)\n", typeDef.Name)
		code += fmt.Sprintf("\t}\n\n")
	}

	// Track used field names again for unmarshal method
	// AIDEV-NOTE: Need to regenerate deduplicated names for unmarshal method
	unmarshalUsedNames := make(map[string]int)

	// Unmarshal fields
	for _, field := range typeDef.Fields {
		baseFieldName := toCamelCase(field.Name)

		// Handle duplicate field names (same logic as struct generation)
		fieldName := baseFieldName
		if count, exists := unmarshalUsedNames[baseFieldName]; exists {
			fieldName = fmt.Sprintf("%s_%d", baseFieldName, count+1)
			unmarshalUsedNames[baseFieldName] = count + 1
		} else {
			unmarshalUsedNames[baseFieldName] = 1
		}

		// AIDEV-NOTE: Always check decoder.Remaining() to prevent panics when fields are missing
		code += fmt.Sprintf("\t// Deserialize `%s`:\n", field.Name)
		code += fmt.Sprintf("\tif decoder.Remaining() > 0 {\n")

		// Check if the field is a complex enum
		if g.isComplexEnum(field.Type) {
			typeName := field.Type.String()
			code += fmt.Sprintf("\t\ttmp := new(%sContainer)\n", strings.ToLower(typeName))
			code += fmt.Sprintf("\t\terr := decoder.Decode(tmp)\n")
			code += fmt.Sprintf("\t\tif err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn err\n")
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t\tswitch tmp.Enum {\n")

			// Get the variants for this enum type
			for i, variant := range typeDef.Variants {
				variantName := variant.Name
				code += fmt.Sprintf("\t\tcase %d:\n", i)
				code += fmt.Sprintf("\t\t\tobj.%s = &tmp.%s\n", fieldName, variantName)
			}

			code += fmt.Sprintf("\t\tdefault:\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"unknown enum index: %%v\", tmp.Enum)\n")
			code += fmt.Sprintf("\t\t}\n")
		} else {
			// option<T> and "optional: true" both arrive as Optional[T]; the
			// wrapper self-unmarshals (presence byte + payload).
			code += fmt.Sprintf("\t\terr = decoder.Decode(&obj.%s)\n", fieldName)
			code += fmt.Sprintf("\t\tif err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn err\n")
			code += fmt.Sprintf("\t\t}\n")
		}

		code += fmt.Sprintf("\t}\n")
	}

	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	return code
}

// generateEnum generates code for an enum type
func (g *TypesGenerator) generateEnum(typeDef idl.TypeDef) string {
	var code string

	// For enums that represent interfaces (like VersionedData), we need to generate an interface type
	// and a container type for serialization/deserialization
	if strings.HasPrefix(typeDef.Name, "Versioned") || typeDef.Name == "InstructionRequest" {
		// Generate interface type
		code += fmt.Sprintf("type %s interface {\n", typeDef.Name)
		code += fmt.Sprintf("\tis%s()\n", typeDef.Name)
		code += "}\n\n"

		// Generate container type for serialization/deserialization
		code += fmt.Sprintf("type %sContainer struct {\n", strings.ToLower(typeDef.Name))
		code += fmt.Sprintf("\tEnum ag_binary.BorshEnum `borsh_enum:\"true\"`\n")
		for _, variant := range typeDef.Variants {
			code += fmt.Sprintf("\t%s %s%sTuple\n", variant.Name, typeDef.Name, variant.Name)
		}
		code += "}\n\n"

		// Generate tuple types for each variant
		for _, variant := range typeDef.Variants {
			code += fmt.Sprintf("type %s%sTuple struct {\n", typeDef.Name, variant.Name)
			if len(variant.Fields) > 0 {
				// For variants with fields, we'll create a tuple with the fields
				for i, field := range variant.Fields {
					fieldType := g.generateFieldType(field.Type)
					code += fmt.Sprintf("\tElem%d %s\n", i, fieldType)
				}
			} else {
				// For variants without fields, we'll create an empty tuple
				code += fmt.Sprintf("\t// Empty tuple\n")
			}
			code += "}\n\n"

			// Add the is<Interface> method to implement the interface
			code += fmt.Sprintf("func (_ %s%sTuple) is%s() {}\n\n", typeDef.Name, variant.Name, typeDef.Name)
		}

		return code
	}

	// Generate discriminator type
	code += fmt.Sprintf("// %sDiscriminator is the type for %s discriminators\n", typeDef.Name, typeDef.Name)
	code += fmt.Sprintf("type %sDiscriminator = uint8\n\n", typeDef.Name)

	// For regular enums, generate a struct with a discriminator and value
	code += fmt.Sprintf("type %s struct {\n", typeDef.Name)
	code += fmt.Sprintf("\tDiscriminator %sDiscriminator\n", typeDef.Name)
	code += fmt.Sprintf("\tValue interface{}\n")
	code += "}\n\n"

	// Generate enum discriminator constants
	code += fmt.Sprintf("// %s discriminator constants\n", typeDef.Name)
	code += fmt.Sprintf("const (\n")
	for i, variant := range typeDef.Variants {
		code += fmt.Sprintf("\t%s%sDiscriminator %sDiscriminator = %d\n", typeDef.Name, variant.Name, typeDef.Name, i)
	}
	code += fmt.Sprintf(")\n\n")

	// Generate variant structs
	for _, variant := range typeDef.Variants {
		if len(variant.Fields) > 0 {
			// Generate struct for variant with fields
			code += fmt.Sprintf("// %s%sVariant represents the %s variant of %s\n", typeDef.Name, variant.Name, variant.Name, typeDef.Name)
			code += fmt.Sprintf("type %s%sVariant struct {\n", typeDef.Name, variant.Name)
			for _, field := range variant.Fields {
				fieldType := g.generateFieldType(field.Type)
				// option<T> and IDL "optional: true" both render as Optional[T].
				if field.Optional && !field.Type.IsOption() {
					code += fmt.Sprintf("\t%s Optional[%s]\n", toCamelCase(field.Name), fieldType)
				} else {
					code += fmt.Sprintf("\t%s %s\n", toCamelCase(field.Name), fieldType)
				}
			}
			code += "}\n\n"

			// Generate MarshalWithEncoder method for the variant struct
			code += fmt.Sprintf("func (obj %s%sVariant) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {\n", typeDef.Name, variant.Name)
			for _, field := range variant.Fields {
				if field.Name == "" {
					// Handle embedded type (unnamed field)
					fieldType := g.generateFieldType(field.Type)
					code += fmt.Sprintf("\t// Serialize embedded type:\n")
					code += fmt.Sprintf("\terr = encoder.Encode(obj.%s)\n", fieldType)
				} else {
					fieldName := toCamelCase(field.Name)
					// Optional[T] handles its own option discriminator via MarshalWithEncoder.
					code += fmt.Sprintf("\t// Serialize `%s` param:\n", field.Name)
					code += fmt.Sprintf("\terr = encoder.Encode(obj.%s)\n", fieldName)
					code += fmt.Sprintf("\tif err != nil {\n")
					code += fmt.Sprintf("\t\treturn err\n")
					code += fmt.Sprintf("\t}\n")
				}
			}
			code += fmt.Sprintf("\treturn nil\n")
			code += fmt.Sprintf("}\n\n")

			// Generate UnmarshalWithDecoder method for the variant struct
			code += fmt.Sprintf("func (obj *%s%sVariant) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {\n", typeDef.Name, variant.Name)
			for _, field := range variant.Fields {
				if field.Name == "" {
					// Handle embedded type (unnamed field)
					fieldType := g.generateFieldType(field.Type)
					code += fmt.Sprintf("\t// Deserialize embedded type:\n")
					code += fmt.Sprintf("\terr = decoder.Decode(&obj.%s)\n", fieldType)
				} else {
					fieldName := toCamelCase(field.Name)
					// Optional[T] handles its own option discriminator via UnmarshalWithDecoder.
					code += fmt.Sprintf("\t// Deserialize `%s`:\n", field.Name)
					code += fmt.Sprintf("\terr = decoder.Decode(&obj.%s)\n", fieldName)
					code += fmt.Sprintf("\tif err != nil {\n")
					code += fmt.Sprintf("\t\treturn err\n")
					code += fmt.Sprintf("\t}\n")
				}
			}
			code += fmt.Sprintf("\treturn nil\n")
			code += fmt.Sprintf("}\n\n")
		}
	}

	// Generate constructor functions for each variant
	for _, variant := range typeDef.Variants {
		if len(variant.Fields) > 0 {
			// Constructor for variant with fields
			code += fmt.Sprintf("// New%s%s creates a new %s with the %s variant\n", typeDef.Name, variant.Name, typeDef.Name, variant.Name)
			code += fmt.Sprintf("func New%s%s(value %s%sVariant) *%s {\n", typeDef.Name, variant.Name, typeDef.Name, variant.Name, typeDef.Name)
			code += fmt.Sprintf("\treturn &%s{\n", typeDef.Name)
			code += fmt.Sprintf("\t\tDiscriminator: %s%sDiscriminator,\n", typeDef.Name, variant.Name)
			code += fmt.Sprintf("\t\tValue: value,\n")
			code += fmt.Sprintf("\t}\n")
			code += "}\n\n"
		} else {
			// Constructor for variant without fields
			code += fmt.Sprintf("// New%s%s creates a new %s with the %s variant\n", typeDef.Name, variant.Name, typeDef.Name, variant.Name)
			code += fmt.Sprintf("func New%s%s() *%s {\n", typeDef.Name, variant.Name, typeDef.Name)
			code += fmt.Sprintf("\treturn &%s{\n", typeDef.Name)
			code += fmt.Sprintf("\t\tDiscriminator: %s%sDiscriminator,\n", typeDef.Name, variant.Name)
			code += fmt.Sprintf("\t\tValue: nil,\n")
			code += fmt.Sprintf("\t}\n")
			code += "}\n\n"
		}
	}

	// Generate Is<Variant> methods
	for _, variant := range typeDef.Variants {
		code += fmt.Sprintf("// Is%s returns true if this %s is the %s variant\n", variant.Name, typeDef.Name, variant.Name)
		code += fmt.Sprintf("func (e *%s) Is%s() bool {\n", typeDef.Name, variant.Name)
		code += fmt.Sprintf("\treturn e.Discriminator == %s%sDiscriminator\n", typeDef.Name, variant.Name)
		code += "}\n\n"
	}

	// Generate Get<Variant> methods
	for _, variant := range typeDef.Variants {
		if len(variant.Fields) > 0 {
			code += fmt.Sprintf("// Get%s returns the %s variant value if this %s is the %s variant\n", variant.Name, variant.Name, typeDef.Name, variant.Name)
			code += fmt.Sprintf("func (e *%s) Get%s() (*%s%sVariant, bool) {\n", typeDef.Name, variant.Name, typeDef.Name, variant.Name)
			code += fmt.Sprintf("\tif !e.Is%s() {\n", variant.Name)
			code += fmt.Sprintf("\t\treturn nil, false\n")
			code += fmt.Sprintf("\t}\n")
			code += fmt.Sprintf("\tvalue, ok := e.Value.(%s%sVariant)\n", typeDef.Name, variant.Name)
			code += fmt.Sprintf("\tif !ok {\n")
			code += fmt.Sprintf("\t\treturn nil, false\n")
			code += fmt.Sprintf("\t}\n")
			code += fmt.Sprintf("\treturn &value, true\n")
			code += "}\n\n"
		}
	}

	// Generate MarshalWithEncoder method
	code += fmt.Sprintf("// MarshalWithEncoder implements binary.EncodableWithEncoder\n")
	code += fmt.Sprintf("func (e *%s) MarshalWithEncoder(encoder *ag_binary.Encoder) error {\n", typeDef.Name)
	code += fmt.Sprintf("\t// Write discriminator\n")
	code += fmt.Sprintf("\tif err := encoder.WriteUint8(uint8(e.Discriminator)); err != nil {\n")
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to write discriminator: %%w\", err)\n")
	code += fmt.Sprintf("\t}\n\n")
	code += fmt.Sprintf("\t// Write variant data\n")
	code += fmt.Sprintf("\tswitch e.Discriminator {\n")
	for _, variant := range typeDef.Variants {
		code += fmt.Sprintf("\tcase %s%sDiscriminator:\n", typeDef.Name, variant.Name)
		if len(variant.Fields) > 0 {
			code += fmt.Sprintf("\t\tvalue, ok := e.Value.(%s%sVariant)\n", typeDef.Name, variant.Name)
			code += fmt.Sprintf("\t\tif !ok {\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"invalid value for %s variant\")\n", variant.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t\tif err := encoder.Encode(value); err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to encode %s variant: %%w\", err)\n", variant.Name)
			code += fmt.Sprintf("\t\t}\n")
		}
	}
	code += fmt.Sprintf("\tdefault:\n")
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"invalid discriminator: %%d\", e.Discriminator)\n")
	code += fmt.Sprintf("\t}\n")
	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	// Generate UnmarshalWithDecoder method
	code += fmt.Sprintf("// UnmarshalWithDecoder implements binary.DecodableWithDecoder\n")
	code += fmt.Sprintf("func (e *%s) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {\n", typeDef.Name)
	code += fmt.Sprintf("\t// Read discriminator\n")
	code += fmt.Sprintf("\tdiscriminator, err := decoder.ReadUint8()\n")
	code += fmt.Sprintf("\tif err != nil {\n")
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"failed to read discriminator: %%w\", err)\n")
	code += fmt.Sprintf("\t}\n")
	code += fmt.Sprintf("\te.Discriminator = %sDiscriminator(discriminator)\n\n", typeDef.Name)
	code += fmt.Sprintf("\t// Read variant data\n")
	code += fmt.Sprintf("\tswitch e.Discriminator {\n")
	for _, variant := range typeDef.Variants {
		code += fmt.Sprintf("\tcase %s%sDiscriminator:\n", typeDef.Name, variant.Name)
		if len(variant.Fields) > 0 {
			code += fmt.Sprintf("\t\tvar value %s%sVariant\n", typeDef.Name, variant.Name)
			code += fmt.Sprintf("\t\tif err := decoder.Decode(&value); err != nil {\n")
			code += fmt.Sprintf("\t\t\treturn fmt.Errorf(\"failed to decode %s variant: %%w\", err)\n", variant.Name)
			code += fmt.Sprintf("\t\t}\n")
			code += fmt.Sprintf("\t\te.Value = value\n")
		}
	}
	code += fmt.Sprintf("\tdefault:\n")
	code += fmt.Sprintf("\t\treturn fmt.Errorf(\"invalid discriminator: %%d\", e.Discriminator)\n")
	code += fmt.Sprintf("\t}\n")
	code += fmt.Sprintf("\treturn nil\n")
	code += fmt.Sprintf("}\n\n")

	return code
}

// generateAlias generates code for an alias type
func (g *TypesGenerator) generateAlias(typeDef idl.TypeDef) string {
	var code string

	// For now, we'll just generate a type alias
	if len(typeDef.Fields) > 0 && typeDef.Fields[0].Type != nil {
		code += fmt.Sprintf("type %s = %s\n\n", typeDef.Name, g.generateFieldType(typeDef.Fields[0].Type))
	} else {
		code += fmt.Sprintf("type %s = interface{}\n\n", typeDef.Name)
	}

	return code
}

// generateFieldType generates Go type for an IDL type
func (g *TypesGenerator) generateFieldType(t idl.Type) string {
	if t.IsBasic() {
		// Map basic types to Go types
		switch t.String() {
		case "bool":
			return "bool"
		case "u8":
			return "uint8"
		case "i8":
			return "int8"
		case "u16":
			return "uint16"
		case "i16":
			return "int16"
		case "u32":
			return "uint32"
		case "i32":
			return "int32"
		case "u64":
			return "uint64"
		case "i64":
			return "int64"
		case "u128":
			return "ag_binary.Uint128"
		case "i128":
			return "ag_binary.Int128"
		case "bytes":
			return "[]byte"
		case "string":
			return "string"
		case "publicKey", "pubkey":
			return "ag_solanago.PublicKey"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		case "unixTimestamp":
			return "ag_solanago.UnixTimeSeconds"
		case "hash":
			return "ag_solanago.Hash"
		case "duration":
			return "ag_solanago.DurationSeconds"
		default:
			return "interface{}"
		}
	} else if t.IsArray() {
		// Handle array types
		arrayType, ok := t.(*types.ArrayType)
		if !ok {
			return "[]interface{}"
		}
		elemType := g.generateFieldType(arrayType.ElemType)
		return fmt.Sprintf("[%d]%s", arrayType.ArraySize, elemType)
	} else if t.IsVector() {
		// Handle vector types
		vecType, ok := t.(*types.VectorType)
		if !ok {
			return "[]interface{}"
		}
		elemType := g.generateFieldType(vecType.ElementType)
		return fmt.Sprintf("[]%s", elemType)
	} else if t.IsOption() {
		// Borsh option<T>: rendered as the generic wrapper Optional[T] whose
		// MarshalWithEncoder/UnmarshalWithDecoder own the discriminator byte.
		optType, ok := t.(*types.OptionType)
		if !ok {
			return "Optional[interface{}]"
		}
		elemType := g.generateFieldType(optType.ElementType)
		return fmt.Sprintf("Optional[%s]", elemType)
	} else if t.IsDefined() {
		// Handle defined types
		return t.String()
	}

	return "interface{}"
}
